//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod workstation_bulk;
pub mod operation_bulk;
pub mod bom_bulk;
pub mod bom_item_bulk;
pub mod bom_operation_bulk;
pub mod work_order_bulk;
pub mod work_order_item_bulk;
pub mod job_card_bulk;

pub use workstation_bulk::WorkstationBulkService;
pub use operation_bulk::OperationBulkService;
pub use bom_bulk::BomBulkService;
pub use bom_item_bulk::BomItemBulkService;
pub use bom_operation_bulk::BomOperationBulkService;
pub use work_order_bulk::WorkOrderBulkService;
pub use work_order_item_bulk::WorkOrderItemBulkService;
pub use job_card_bulk::JobCardBulkService;

// <<< CUSTOM
// END CUSTOM
