//! Bulk operations for WorkOrder entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateWorkOrderDto;
use crate::application::service::WorkOrderService;
use crate::domain::entity::WorkOrder;

/// Bulk operation handler for WorkOrder entities.
///
/// Wraps `WorkOrderService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type WorkOrderBulkService = GenericBulkService<WorkOrder, CreateWorkOrderDto, WorkOrderService>;

// <<< CUSTOM
// END CUSTOM
