//! Bulk operations for WorkOrderItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateWorkOrderItemDto;
use crate::application::service::WorkOrderItemService;
use crate::domain::entity::WorkOrderItem;

/// Bulk operation handler for WorkOrderItem entities.
///
/// Wraps `WorkOrderItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type WorkOrderItemBulkService = GenericBulkService<WorkOrderItem, CreateWorkOrderItemDto, WorkOrderItemService>;

// <<< CUSTOM
// END CUSTOM
