//! Bulk operations for Workstation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateWorkstationDto;
use crate::application::service::WorkstationService;
use crate::domain::entity::Workstation;

/// Bulk operation handler for Workstation entities.
///
/// Wraps `WorkstationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type WorkstationBulkService = GenericBulkService<Workstation, CreateWorkstationDto, WorkstationService>;

// <<< CUSTOM
// END CUSTOM
