//! BomSubcontractor DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BomSubcontractor;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BomSubcontractor
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBomSubcontractorDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bom_id")]
    pub bom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "partner_id")]
    pub partner_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BomSubcontractor
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBomSubcontractorDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bom_id")]
    pub bom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "partner_id")]
    pub partner_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BomSubcontractor
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBomSubcontractorDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bom_id")]
    pub bom_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "partner_id")]
    pub partner_id: Option<Uuid>,
}

impl PatchBomSubcontractorDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.bom_id.is_some() || self.partner_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BomSubcontractor entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomSubcontractorResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub partner_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BomSubcontractor entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomSubcontractorListResponseDto {
    /// List of items
    pub items: Vec<BomSubcontractorResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BomSubcontractorListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BomSubcontractorResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomSubcontractorSummaryDto {
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    pub bom_id: Uuid,
    pub partner_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BomSubcontractor> for BomSubcontractorResponseDto {
    fn from(entity: BomSubcontractor) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bom_id: entity.bom_id,
            partner_id: entity.partner_id,
            metadata: entity.metadata,
        }
    }
}

impl From<BomSubcontractor> for BomSubcontractorSummaryDto {
    fn from(entity: BomSubcontractor) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bom_id: entity.bom_id,
            partner_id: entity.partner_id,
            created_at,
        }
    }
}

impl From<CreateBomSubcontractorDto> for BomSubcontractor {
    fn from(dto: CreateBomSubcontractorDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            bom_id: dto.bom_id,
            partner_id: dto.partner_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BomSubcontractor> for BomSubcontractorResponseDto {
    fn from(entity: &BomSubcontractor) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            bom_id: entity.bom_id.clone(),
            partner_id: entity.partner_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBomSubcontractorDto> for BomSubcontractor {
    fn from_create_dto(dto: CreateBomSubcontractorDto) -> backbone_core::ServiceResult<Self> {
        Ok(BomSubcontractor::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBomSubcontractorDto> for BomSubcontractor {
    fn apply_update(mut self, dto: UpdateBomSubcontractorDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.bom_id = dto.bom_id;
        self.partner_id = dto.partner_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BomSubcontractor here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
