//! Bom DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Bom;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Bom
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBomDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "bom_code")]
    pub bom_code: String,
    pub quantity: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "raw_material_cost")]
    pub raw_material_cost: Decimal,
    #[serde(alias = "operating_cost")]
    pub operating_cost: Decimal,
    #[serde(alias = "total_cost")]
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_default")]
    pub is_default: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Bom
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBomDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "bom_code")]
    pub bom_code: String,
    pub quantity: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "raw_material_cost")]
    pub raw_material_cost: Decimal,
    #[serde(alias = "operating_cost")]
    pub operating_cost: Decimal,
    #[serde(alias = "total_cost")]
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_default")]
    pub is_default: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Bom
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBomDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bom_code")]
    pub bom_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "raw_material_cost")]
    pub raw_material_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "operating_cost")]
    pub operating_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_cost")]
    pub total_cost: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_default")]
    pub is_default: Option<bool>,
}

impl PatchBomDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.item_id.is_some() || self.bom_code.is_some() || self.quantity.is_some() || self.uom.is_some() || self.currency.is_some() || self.raw_material_cost.is_some() || self.operating_cost.is_some() || self.total_cost.is_some() || self.is_active.is_some() || self.is_default.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Bom entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub bom_code: String,
    pub quantity: Decimal,
    pub uom: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub raw_material_cost: Decimal,
    pub operating_cost: Decimal,
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_default: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Bom entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomListResponseDto {
    /// List of items
    pub items: Vec<BomResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BomListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BomResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BomSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub bom_code: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Bom> for BomResponseDto {
    fn from(entity: Bom) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            bom_code: entity.bom_code,
            quantity: entity.quantity,
            uom: entity.uom,
            currency: entity.currency,
            raw_material_cost: entity.raw_material_cost,
            operating_cost: entity.operating_cost,
            total_cost: entity.total_cost,
            is_active: entity.is_active,
            is_default: entity.is_default,
            metadata: entity.metadata,
        }
    }
}

impl From<Bom> for BomSummaryDto {
    fn from(entity: Bom) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            bom_code: entity.bom_code,
            created_at,
        }
    }
}

impl From<CreateBomDto> for Bom {
    fn from(dto: CreateBomDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            item_id: dto.item_id,
            bom_code: dto.bom_code,
            quantity: dto.quantity,
            uom: dto.uom,
            currency: dto.currency,
            raw_material_cost: dto.raw_material_cost,
            operating_cost: dto.operating_cost,
            total_cost: dto.total_cost,
            is_active: dto.is_active,
            is_default: dto.is_default,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Bom> for BomResponseDto {
    fn from(entity: &Bom) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            item_id: entity.item_id.clone(),
            bom_code: entity.bom_code.clone(),
            quantity: entity.quantity.clone(),
            uom: entity.uom.clone(),
            currency: entity.currency.clone(),
            raw_material_cost: entity.raw_material_cost.clone(),
            operating_cost: entity.operating_cost.clone(),
            total_cost: entity.total_cost.clone(),
            is_active: entity.is_active.clone(),
            is_default: entity.is_default.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBomDto> for Bom {
    fn from_create_dto(dto: CreateBomDto) -> backbone_core::ServiceResult<Self> {
        Ok(Bom::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBomDto> for Bom {
    fn apply_update(mut self, dto: UpdateBomDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.item_id = dto.item_id;
        self.bom_code = dto.bom_code;
        self.quantity = dto.quantity;
        self.uom = dto.uom;
        self.currency = dto.currency;
        self.raw_material_cost = dto.raw_material_cost;
        self.operating_cost = dto.operating_cost;
        self.total_cost = dto.total_cost;
        self.is_active = dto.is_active;
        self.is_default = dto.is_default;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Bom here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
