//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod workstation_dto;
pub mod workstation_loss_dto;
pub mod workstation_productivity_dto;
pub mod operation_dto;
pub mod bom_dto;
pub mod bom_item_dto;
pub mod bom_operation_dto;
pub mod bom_byproduct_dto;
pub mod bom_subcontractor_dto;
pub mod category_costing_defaults_dto;
pub mod repair_order_dto;
pub mod repair_part_dto;
pub mod repair_tag_dto;
pub mod unbuild_order_dto;
pub mod work_order_dto;
pub mod work_order_item_dto;
pub mod job_card_dto;
pub mod subcontract_mo_link_dto;

// Re-exports
pub use workstation_dto::{
    CreateWorkstationDto,
    UpdateWorkstationDto,
    PatchWorkstationDto,
    WorkstationResponseDto,
    WorkstationListResponseDto,
    WorkstationSummaryDto,
};
pub use workstation_loss_dto::{
    CreateWorkstationLossDto,
    UpdateWorkstationLossDto,
    PatchWorkstationLossDto,
    WorkstationLossResponseDto,
    WorkstationLossListResponseDto,
    WorkstationLossSummaryDto,
};
pub use workstation_productivity_dto::{
    CreateWorkstationProductivityDto,
    UpdateWorkstationProductivityDto,
    PatchWorkstationProductivityDto,
    WorkstationProductivityResponseDto,
    WorkstationProductivityListResponseDto,
    WorkstationProductivitySummaryDto,
};
pub use operation_dto::{
    CreateOperationDto,
    UpdateOperationDto,
    PatchOperationDto,
    OperationResponseDto,
    OperationListResponseDto,
    OperationSummaryDto,
};
pub use bom_dto::{
    CreateBomDto,
    UpdateBomDto,
    PatchBomDto,
    BomResponseDto,
    BomListResponseDto,
    BomSummaryDto,
};
pub use bom_item_dto::{
    CreateBomItemDto,
    UpdateBomItemDto,
    PatchBomItemDto,
    BomItemResponseDto,
    BomItemListResponseDto,
    BomItemSummaryDto,
};
pub use bom_operation_dto::{
    CreateBomOperationDto,
    UpdateBomOperationDto,
    PatchBomOperationDto,
    BomOperationResponseDto,
    BomOperationListResponseDto,
    BomOperationSummaryDto,
};
pub use bom_byproduct_dto::{
    CreateBomByproductDto,
    UpdateBomByproductDto,
    PatchBomByproductDto,
    BomByproductResponseDto,
    BomByproductListResponseDto,
    BomByproductSummaryDto,
};
pub use bom_subcontractor_dto::{
    CreateBomSubcontractorDto,
    UpdateBomSubcontractorDto,
    PatchBomSubcontractorDto,
    BomSubcontractorResponseDto,
    BomSubcontractorListResponseDto,
    BomSubcontractorSummaryDto,
};
pub use category_costing_defaults_dto::{
    CreateCategoryCostingDefaultsDto,
    UpdateCategoryCostingDefaultsDto,
    PatchCategoryCostingDefaultsDto,
    CategoryCostingDefaultsResponseDto,
    CategoryCostingDefaultsListResponseDto,
    CategoryCostingDefaultsSummaryDto,
};
pub use repair_order_dto::{
    CreateRepairOrderDto,
    UpdateRepairOrderDto,
    PatchRepairOrderDto,
    RepairOrderResponseDto,
    RepairOrderListResponseDto,
    RepairOrderSummaryDto,
};
pub use repair_part_dto::{
    CreateRepairPartDto,
    UpdateRepairPartDto,
    PatchRepairPartDto,
    RepairPartResponseDto,
    RepairPartListResponseDto,
    RepairPartSummaryDto,
};
pub use repair_tag_dto::{
    CreateRepairTagDto,
    UpdateRepairTagDto,
    PatchRepairTagDto,
    RepairTagResponseDto,
    RepairTagListResponseDto,
    RepairTagSummaryDto,
};
pub use unbuild_order_dto::{
    CreateUnbuildOrderDto,
    UpdateUnbuildOrderDto,
    PatchUnbuildOrderDto,
    UnbuildOrderResponseDto,
    UnbuildOrderListResponseDto,
    UnbuildOrderSummaryDto,
};
pub use work_order_dto::{
    CreateWorkOrderDto,
    UpdateWorkOrderDto,
    PatchWorkOrderDto,
    WorkOrderResponseDto,
    WorkOrderListResponseDto,
    WorkOrderSummaryDto,
};
pub use work_order_item_dto::{
    CreateWorkOrderItemDto,
    UpdateWorkOrderItemDto,
    PatchWorkOrderItemDto,
    WorkOrderItemResponseDto,
    WorkOrderItemListResponseDto,
    WorkOrderItemSummaryDto,
};
pub use job_card_dto::{
    CreateJobCardDto,
    UpdateJobCardDto,
    PatchJobCardDto,
    JobCardResponseDto,
    JobCardListResponseDto,
    JobCardSummaryDto,
};
pub use subcontract_mo_link_dto::{
    CreateSubcontractMoLinkDto,
    UpdateSubcontractMoLinkDto,
    PatchSubcontractMoLinkDto,
    SubcontractMoLinkResponseDto,
    SubcontractMoLinkListResponseDto,
    SubcontractMoLinkSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
