//! UnbuildOrder DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::UnbuildOrder;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::UnbuildStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new UnbuildOrder
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateUnbuildOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "unbuild_number")]
    pub unbuild_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "work_order_id")]
    pub work_order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub status: UnbuildStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a UnbuildOrder
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateUnbuildOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "unbuild_number")]
    pub unbuild_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "work_order_id")]
    pub work_order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub status: UnbuildStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a UnbuildOrder
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchUnbuildOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "unbuild_number")]
    pub unbuild_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "work_order_id")]
    pub work_order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<UnbuildStatus>,
}

impl PatchUnbuildOrderDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.unbuild_number.is_some() || self.work_order_id.is_some() || self.item_id.is_some() || self.quantity.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for UnbuildOrder entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UnbuildOrderResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub unbuild_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub work_order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub status: UnbuildStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for UnbuildOrder entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UnbuildOrderListResponseDto {
    /// List of items
    pub items: Vec<UnbuildOrderResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl UnbuildOrderListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<UnbuildOrderResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UnbuildOrderSummaryDto {
    pub id: Uuid,
    pub unbuild_number: String,
    pub work_order_id: Uuid,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<UnbuildOrder> for UnbuildOrderResponseDto {
    fn from(entity: UnbuildOrder) -> Self {
        Self {
            id: entity.id,
            unbuild_number: entity.unbuild_number,
            work_order_id: entity.work_order_id,
            item_id: entity.item_id,
            quantity: entity.quantity,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<UnbuildOrder> for UnbuildOrderSummaryDto {
    fn from(entity: UnbuildOrder) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            unbuild_number: entity.unbuild_number,
            work_order_id: entity.work_order_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateUnbuildOrderDto> for UnbuildOrder {
    fn from(dto: CreateUnbuildOrderDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            unbuild_number: dto.unbuild_number,
            work_order_id: dto.work_order_id,
            item_id: dto.item_id,
            quantity: dto.quantity,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&UnbuildOrder> for UnbuildOrderResponseDto {
    fn from(entity: &UnbuildOrder) -> Self {
        Self {
            id: entity.id.clone(),
            unbuild_number: entity.unbuild_number.clone(),
            work_order_id: entity.work_order_id.clone(),
            item_id: entity.item_id.clone(),
            quantity: entity.quantity.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateUnbuildOrderDto> for UnbuildOrder {
    fn from_create_dto(dto: CreateUnbuildOrderDto) -> backbone_core::ServiceResult<Self> {
        Ok(UnbuildOrder::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateUnbuildOrderDto> for UnbuildOrder {
    fn apply_update(mut self, dto: UpdateUnbuildOrderDto) -> backbone_core::ServiceResult<Self> {
        self.unbuild_number = dto.unbuild_number;
        self.work_order_id = dto.work_order_id;
        self.item_id = dto.item_id;
        self.quantity = dto.quantity;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to UnbuildOrder here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
