//! WorkstationProductivity DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WorkstationProductivity;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WorkstationProductivity
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWorkstationProductivityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "workstation_id")]
    pub workstation_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "job_card_id")]
    pub job_card_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "loss_id")]
    pub loss_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "date_start")]
    pub date_start: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_end")]
    pub date_end: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WorkstationProductivity
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWorkstationProductivityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "workstation_id")]
    pub workstation_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "job_card_id")]
    pub job_card_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "loss_id")]
    pub loss_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "date_start")]
    pub date_start: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_end")]
    pub date_end: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WorkstationProductivity
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWorkstationProductivityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "workstation_id")]
    pub workstation_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "job_card_id")]
    pub job_card_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "loss_id")]
    pub loss_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_start")]
    pub date_start: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_end")]
    pub date_end: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchWorkstationProductivityDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.workstation_id.is_some() || self.job_card_id.is_some() || self.loss_id.is_some() || self.date_start.is_some() || self.date_end.is_some() || self.description.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WorkstationProductivity entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkstationProductivityResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub workstation_id: Uuid,
    pub job_card_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub loss_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub date_start: DateTime<Utc>,
    pub date_end: Option<DateTime<Utc>>,
    pub description: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WorkstationProductivity entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkstationProductivityListResponseDto {
    /// List of items
    pub items: Vec<WorkstationProductivityResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WorkstationProductivityListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WorkstationProductivityResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkstationProductivitySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub workstation_id: Uuid,
    pub job_card_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WorkstationProductivity> for WorkstationProductivityResponseDto {
    fn from(entity: WorkstationProductivity) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            workstation_id: entity.workstation_id,
            job_card_id: entity.job_card_id,
            loss_id: entity.loss_id,
            date_start: entity.date_start,
            date_end: entity.date_end,
            description: entity.description,
            metadata: entity.metadata,
        }
    }
}

impl From<WorkstationProductivity> for WorkstationProductivitySummaryDto {
    fn from(entity: WorkstationProductivity) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            workstation_id: entity.workstation_id,
            job_card_id: entity.job_card_id,
            created_at,
        }
    }
}

impl From<CreateWorkstationProductivityDto> for WorkstationProductivity {
    fn from(dto: CreateWorkstationProductivityDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            workstation_id: dto.workstation_id,
            job_card_id: dto.job_card_id,
            loss_id: dto.loss_id,
            date_start: dto.date_start,
            date_end: dto.date_end,
            description: dto.description,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WorkstationProductivity> for WorkstationProductivityResponseDto {
    fn from(entity: &WorkstationProductivity) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            workstation_id: entity.workstation_id.clone(),
            job_card_id: entity.job_card_id.clone(),
            loss_id: entity.loss_id.clone(),
            date_start: entity.date_start.clone(),
            date_end: entity.date_end.clone(),
            description: entity.description.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWorkstationProductivityDto> for WorkstationProductivity {
    fn from_create_dto(dto: CreateWorkstationProductivityDto) -> backbone_core::ServiceResult<Self> {
        Ok(WorkstationProductivity::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWorkstationProductivityDto> for WorkstationProductivity {
    fn apply_update(mut self, dto: UpdateWorkstationProductivityDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.workstation_id = dto.workstation_id;
        self.job_card_id = dto.job_card_id;
        self.loss_id = dto.loss_id;
        self.date_start = dto.date_start;
        self.date_end = dto.date_end;
        self.description = dto.description;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WorkstationProductivity here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
