//! WorkOrder DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WorkOrder;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WorkOrderStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WorkOrder
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWorkOrderDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "work_order_number")]
    pub work_order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bom_id")]
    pub bom_id: Uuid,
    pub quantity: Decimal,
    #[serde(alias = "produced_qty")]
    pub produced_qty: Decimal,
    pub status: WorkOrderStatus,
    #[serde(alias = "raw_material_cost")]
    pub raw_material_cost: Decimal,
    #[serde(alias = "operating_cost")]
    pub operating_cost: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wip_warehouse_id")]
    pub wip_warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fg_warehouse_id")]
    pub fg_warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wip_account_id")]
    pub wip_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fg_account_id")]
    pub fg_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "raw_material_account_id")]
    pub raw_material_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "conversion_cost_account_id")]
    pub conversion_cost_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "planned_start_date")]
    pub planned_start_date: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WorkOrder
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWorkOrderDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "work_order_number")]
    pub work_order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bom_id")]
    pub bom_id: Uuid,
    pub quantity: Decimal,
    #[serde(alias = "produced_qty")]
    pub produced_qty: Decimal,
    pub status: WorkOrderStatus,
    #[serde(alias = "raw_material_cost")]
    pub raw_material_cost: Decimal,
    #[serde(alias = "operating_cost")]
    pub operating_cost: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wip_warehouse_id")]
    pub wip_warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fg_warehouse_id")]
    pub fg_warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wip_account_id")]
    pub wip_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fg_account_id")]
    pub fg_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "raw_material_account_id")]
    pub raw_material_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "conversion_cost_account_id")]
    pub conversion_cost_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "planned_start_date")]
    pub planned_start_date: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WorkOrder
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWorkOrderDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "work_order_number")]
    pub work_order_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bom_id")]
    pub bom_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "produced_qty")]
    pub produced_qty: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<WorkOrderStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "raw_material_cost")]
    pub raw_material_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "operating_cost")]
    pub operating_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "wip_warehouse_id")]
    pub wip_warehouse_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "fg_warehouse_id")]
    pub fg_warehouse_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "wip_account_id")]
    pub wip_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "fg_account_id")]
    pub fg_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "raw_material_account_id")]
    pub raw_material_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "conversion_cost_account_id")]
    pub conversion_cost_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "planned_start_date")]
    pub planned_start_date: Option<DateTime<Utc>>,
}

impl PatchWorkOrderDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.work_order_number.is_some() || self.item_id.is_some() || self.bom_id.is_some() || self.quantity.is_some() || self.produced_qty.is_some() || self.status.is_some() || self.raw_material_cost.is_some() || self.operating_cost.is_some() || self.wip_warehouse_id.is_some() || self.fg_warehouse_id.is_some() || self.wip_account_id.is_some() || self.fg_account_id.is_some() || self.raw_material_account_id.is_some() || self.conversion_cost_account_id.is_some() || self.planned_start_date.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WorkOrder entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkOrderResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub work_order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub produced_qty: Decimal,
    pub status: WorkOrderStatus,
    pub raw_material_cost: Decimal,
    pub operating_cost: Decimal,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
    pub planned_start_date: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WorkOrder entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkOrderListResponseDto {
    /// List of items
    pub items: Vec<WorkOrderResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WorkOrderListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WorkOrderResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WorkOrderSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub work_order_number: String,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WorkOrder> for WorkOrderResponseDto {
    fn from(entity: WorkOrder) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            work_order_number: entity.work_order_number,
            item_id: entity.item_id,
            bom_id: entity.bom_id,
            quantity: entity.quantity,
            produced_qty: entity.produced_qty,
            status: entity.status,
            raw_material_cost: entity.raw_material_cost,
            operating_cost: entity.operating_cost,
            wip_warehouse_id: entity.wip_warehouse_id,
            fg_warehouse_id: entity.fg_warehouse_id,
            wip_account_id: entity.wip_account_id,
            fg_account_id: entity.fg_account_id,
            raw_material_account_id: entity.raw_material_account_id,
            conversion_cost_account_id: entity.conversion_cost_account_id,
            planned_start_date: entity.planned_start_date,
            metadata: entity.metadata,
        }
    }
}

impl From<WorkOrder> for WorkOrderSummaryDto {
    fn from(entity: WorkOrder) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            work_order_number: entity.work_order_number,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateWorkOrderDto> for WorkOrder {
    fn from(dto: CreateWorkOrderDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            work_order_number: dto.work_order_number,
            item_id: dto.item_id,
            bom_id: dto.bom_id,
            quantity: dto.quantity,
            produced_qty: dto.produced_qty,
            status: dto.status,
            raw_material_cost: dto.raw_material_cost,
            operating_cost: dto.operating_cost,
            wip_warehouse_id: dto.wip_warehouse_id,
            fg_warehouse_id: dto.fg_warehouse_id,
            wip_account_id: dto.wip_account_id,
            fg_account_id: dto.fg_account_id,
            raw_material_account_id: dto.raw_material_account_id,
            conversion_cost_account_id: dto.conversion_cost_account_id,
            planned_start_date: dto.planned_start_date,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WorkOrder> for WorkOrderResponseDto {
    fn from(entity: &WorkOrder) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            work_order_number: entity.work_order_number.clone(),
            item_id: entity.item_id.clone(),
            bom_id: entity.bom_id.clone(),
            quantity: entity.quantity.clone(),
            produced_qty: entity.produced_qty.clone(),
            status: entity.status.clone(),
            raw_material_cost: entity.raw_material_cost.clone(),
            operating_cost: entity.operating_cost.clone(),
            wip_warehouse_id: entity.wip_warehouse_id.clone(),
            fg_warehouse_id: entity.fg_warehouse_id.clone(),
            wip_account_id: entity.wip_account_id.clone(),
            fg_account_id: entity.fg_account_id.clone(),
            raw_material_account_id: entity.raw_material_account_id.clone(),
            conversion_cost_account_id: entity.conversion_cost_account_id.clone(),
            planned_start_date: entity.planned_start_date.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWorkOrderDto> for WorkOrder {
    fn from_create_dto(dto: CreateWorkOrderDto) -> backbone_core::ServiceResult<Self> {
        Ok(WorkOrder::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWorkOrderDto> for WorkOrder {
    fn apply_update(mut self, dto: UpdateWorkOrderDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.work_order_number = dto.work_order_number;
        self.item_id = dto.item_id;
        self.bom_id = dto.bom_id;
        self.quantity = dto.quantity;
        self.produced_qty = dto.produced_qty;
        self.status = dto.status;
        self.raw_material_cost = dto.raw_material_cost;
        self.operating_cost = dto.operating_cost;
        self.wip_warehouse_id = dto.wip_warehouse_id;
        self.fg_warehouse_id = dto.fg_warehouse_id;
        self.wip_account_id = dto.wip_account_id;
        self.fg_account_id = dto.fg_account_id;
        self.raw_material_account_id = dto.raw_material_account_id;
        self.conversion_cost_account_id = dto.conversion_cost_account_id;
        self.planned_start_date = dto.planned_start_date;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WorkOrder here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
