//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod workstation_specification;
pub mod operation_specification;
pub mod bom_specification;
pub mod bom_item_specification;
pub mod bom_operation_specification;
pub mod work_order_specification;
pub mod work_order_item_specification;
pub mod job_card_specification;

// <<< CUSTOM
// END CUSTOM
