//! Domain policy for Bom aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Bom;

/// Domain policy for Bom — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Bom>` in the `// <<< CUSTOM` zone.
pub type BomDomainPolicy = PermitAllPolicy<Bom>;

// <<< CUSTOM
// END CUSTOM
