//! Domain policy for BomOperation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::BomOperation;

/// Domain policy for BomOperation — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<BomOperation>` in the `// <<< CUSTOM` zone.
pub type BomOperationDomainPolicy = PermitAllPolicy<BomOperation>;

// <<< CUSTOM
// END CUSTOM
