//! Domain policy for Workstation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Workstation;

/// Domain policy for Workstation — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Workstation>` in the `// <<< CUSTOM` zone.
pub type WorkstationDomainPolicy = PermitAllPolicy<Workstation>;

// <<< CUSTOM
// END CUSTOM
