//! Application service for BomItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bom_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBomItemDto, UpdateBomItemDto};
use crate::domain::entity::BomItem;
use crate::infrastructure::persistence::BomItemRepository;

/// Application service for BomItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bom_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BomItemServiceCustom {
///     inner: Arc<BomItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BomItemService = GenericCrudService<
    BomItem,
    CreateBomItemDto,
    UpdateBomItemDto,
    BomItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
