//! Application service for CategoryCostingDefaults entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `category_costing_defaults_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCategoryCostingDefaultsDto, UpdateCategoryCostingDefaultsDto};
use crate::domain::entity::CategoryCostingDefaults;
use crate::infrastructure::persistence::CategoryCostingDefaultsRepository;

/// Application service for CategoryCostingDefaults entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `category_costing_defaults_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CategoryCostingDefaultsServiceCustom {
///     inner: Arc<CategoryCostingDefaultsService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CategoryCostingDefaultsService = GenericCrudService<
    CategoryCostingDefaults,
    CreateCategoryCostingDefaultsDto,
    UpdateCategoryCostingDefaultsDto,
    CategoryCostingDefaultsRepository,
>;

// <<< CUSTOM
// END CUSTOM
