//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod workstation_service;
pub mod operation_service;
pub mod bom_service;
pub mod bom_item_service;
pub mod bom_operation_service;
pub mod work_order_service;
pub mod work_order_item_service;
pub mod job_card_service;

// <<< CUSTOM
pub mod manufacturing_gl;
pub mod manufacturing_ports;
pub mod manufacturing_events;
pub mod manufacturing_write_service;
// END CUSTOM

pub use workstation_service::WorkstationService;
pub use operation_service::OperationService;
pub use bom_service::BomService;
pub use bom_item_service::BomItemService;
pub use bom_operation_service::BomOperationService;
pub use work_order_service::WorkOrderService;
pub use work_order_item_service::WorkOrderItemService;
pub use job_card_service::JobCardService;
// <<< CUSTOM
pub use manufacturing_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use manufacturing_ports::{
    FinishedReceipt, InventoryPort, InventoryRejected, IssueLine, IssuedLineValue, IssueAck,
    MaterialIssue,
};
pub use manufacturing_events::{
    ConversionCharged, FinishedGoodsReceived, LoggingSink, ManufacturingEvent,
    ManufacturingEventSink, MaterialsConsumed, WorkOrderCompleted, WorkOrderReleased,
};
pub use manufacturing_write_service::{
    ConsumeOutcome, ManufacturingError, ManufacturingWriteService, NewBom, NewBomItem,
    NewBomOperation, NewJobCard, NewWorkOrder, ReceiveOutcome,
};
// END CUSTOM