//! Application service for UnbuildOrder entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `unbuild_order_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateUnbuildOrderDto, UpdateUnbuildOrderDto};
use crate::domain::entity::UnbuildOrder;
use crate::infrastructure::persistence::UnbuildOrderRepository;

/// Application service for UnbuildOrder entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `unbuild_order_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct UnbuildOrderServiceCustom {
///     inner: Arc<UnbuildOrderService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type UnbuildOrderService = GenericCrudService<
    UnbuildOrder,
    CreateUnbuildOrderDto,
    UpdateUnbuildOrderDto,
    UnbuildOrderRepository,
>;

// <<< CUSTOM
// END CUSTOM
