//! Application service for Workstation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `workstation_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWorkstationDto, UpdateWorkstationDto};
use crate::domain::entity::Workstation;
use crate::infrastructure::persistence::WorkstationRepository;

/// Application service for Workstation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `workstation_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WorkstationServiceCustom {
///     inner: Arc<WorkstationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WorkstationService = GenericCrudService<
    Workstation,
    CreateWorkstationDto,
    UpdateWorkstationDto,
    WorkstationRepository,
>;

// <<< CUSTOM
// END CUSTOM
