-- BomSubcontractor Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the manufacturing.bom_subcontractors table.
-- Customize this file to add your initial data.

-- INSERT INTO manufacturing.bom_subcontractors (
--     id,
--     company_id,
--     bom_id,
--     partner_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO manufacturing.bom_subcontractors (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

