-- CategoryCostingDefaults Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the manufacturing.category_costing_defaults table.
-- Customize this file to add your initial data.

-- INSERT INTO manufacturing.category_costing_defaults (
--     id,
--     company_id,
--     product_category_id,
--     wip_account_id,
--     fg_account_id,
--     raw_material_account_id,
--     conversion_cost_account_id,
--     subcontract_interim_account_id,
--     cost_variance_account_id,
--     inventory_loss_account_id,
--     repair_expense_account_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO manufacturing.category_costing_defaults (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

