-- SubcontractMoLink Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the manufacturing.subcontract_mo_links table.
-- Customize this file to add your initial data.

-- INSERT INTO manufacturing.subcontract_mo_links (
--     id,
--     company_id,
--     purchase_order_id,
--     work_order_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO manufacturing.subcontract_mo_links (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

