-- UnbuildOrder Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the manufacturing.unbuild_orders table.
-- Customize this file to add your initial data.

-- INSERT INTO manufacturing.unbuild_orders (
--     id,
--     company_id,
--     unbuild_number,
--     work_order_id,
--     item_id,
--     quantity,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO manufacturing.unbuild_orders (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

