-- WorkstationProductivity Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the manufacturing.workstation_productivity table.
-- Customize this file to add your initial data.

-- INSERT INTO manufacturing.workstation_productivity (
--     id,
--     company_id,
--     workstation_id,
--     job_card_id,
--     loss_id,
--     date_start,
--     date_end,
--     description,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO manufacturing.workstation_productivity (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

