-- Migration: Create bom_subcontractors table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS manufacturing;

CREATE TABLE IF NOT EXISTS manufacturing.bom_subcontractors (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID,
    bom_id UUID NOT NULL,
    partner_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bom_subcontractors_bom_id_partner_id ON manufacturing.bom_subcontractors (bom_id, partner_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bom_subcontractors_metadata_gin ON manufacturing.bom_subcontractors USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bom_subcontractors_metadata_deleted_at ON manufacturing.bom_subcontractors ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bom_subcontractors_metadata_created_at ON manufacturing.bom_subcontractors ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bom_subcontractors_metadata_updated_at ON manufacturing.bom_subcontractors ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION manufacturing.bom_subcontractors_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bom_subcontractors_insert_audit ON manufacturing.bom_subcontractors;
CREATE TRIGGER bom_subcontractors_insert_audit BEFORE INSERT ON manufacturing.bom_subcontractors
    FOR EACH ROW EXECUTE FUNCTION manufacturing.bom_subcontractors_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bom_subcontractors_update_audit ON manufacturing.bom_subcontractors;
CREATE TRIGGER bom_subcontractors_update_audit BEFORE UPDATE ON manufacturing.bom_subcontractors
    FOR EACH ROW EXECUTE FUNCTION manufacturing.bom_subcontractors_audit_timestamp();
