-- Migration: Create workstation_productivity table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS manufacturing;

CREATE TABLE IF NOT EXISTS manufacturing.workstation_productivity (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    workstation_id UUID NOT NULL,
    job_card_id UUID,
    loss_id UUID NOT NULL,
    date_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_end TIMESTAMPTZ,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_workstation_productivity_workstation_id_date_start ON manufacturing.workstation_productivity (workstation_id, date_start);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_workstation_productivity_metadata_gin ON manufacturing.workstation_productivity USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_workstation_productivity_metadata_deleted_at ON manufacturing.workstation_productivity ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_workstation_productivity_metadata_created_at ON manufacturing.workstation_productivity ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_workstation_productivity_metadata_updated_at ON manufacturing.workstation_productivity ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION manufacturing.workstation_productivity_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workstation_productivity_insert_audit ON manufacturing.workstation_productivity;
CREATE TRIGGER workstation_productivity_insert_audit BEFORE INSERT ON manufacturing.workstation_productivity
    FOR EACH ROW EXECUTE FUNCTION manufacturing.workstation_productivity_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workstation_productivity_update_audit ON manufacturing.workstation_productivity;
CREATE TRIGGER workstation_productivity_update_audit BEFORE UPDATE ON manufacturing.workstation_productivity
    FOR EACH ROW EXECUTE FUNCTION manufacturing.workstation_productivity_audit_timestamp();
