-- Migration: Create workstation_losses table
-- Generated by metaphor-schema

-- Create loss_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loss_type') THEN
        CREATE TYPE loss_type AS ENUM ('productive', 'availability', 'performance', 'quality');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS manufacturing;

CREATE TABLE IF NOT EXISTS manufacturing.workstation_losses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID,
    name TEXT NOT NULL,
    loss_type loss_type NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_workstation_losses_company_id_name ON manufacturing.workstation_losses (company_id, name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_workstation_losses_metadata_gin ON manufacturing.workstation_losses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_workstation_losses_metadata_deleted_at ON manufacturing.workstation_losses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_workstation_losses_metadata_created_at ON manufacturing.workstation_losses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_workstation_losses_metadata_updated_at ON manufacturing.workstation_losses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION manufacturing.workstation_losses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workstation_losses_insert_audit ON manufacturing.workstation_losses;
CREATE TRIGGER workstation_losses_insert_audit BEFORE INSERT ON manufacturing.workstation_losses
    FOR EACH ROW EXECUTE FUNCTION manufacturing.workstation_losses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workstation_losses_update_audit ON manufacturing.workstation_losses;
CREATE TRIGGER workstation_losses_update_audit BEFORE UPDATE ON manufacturing.workstation_losses
    FOR EACH ROW EXECUTE FUNCTION manufacturing.workstation_losses_audit_timestamp();
