//! Domain events for BomByproduct entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BomByproduct;

/// Domain events for BomByproduct — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BomByproduct>)` variant.
pub type BomByproductEvent = CrudEvent<BomByproduct>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BomByproduct events.
pub type BomByproductEventPublisher = Arc<dyn CrudEventPublisher<BomByproduct> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBomByproductEventPublisher = NoOpCrudEventPublisher<BomByproduct>;
