//! Domain events for BomSubcontractor entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BomSubcontractor;

/// Domain events for BomSubcontractor — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BomSubcontractor>)` variant.
pub type BomSubcontractorEvent = CrudEvent<BomSubcontractor>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BomSubcontractor events.
pub type BomSubcontractorEventPublisher = Arc<dyn CrudEventPublisher<BomSubcontractor> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBomSubcontractorEventPublisher = NoOpCrudEventPublisher<BomSubcontractor>;
