//! Event handler trait for BomItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BomItemEvent;

/// Event handler for BomItem events.
/// Implement this trait to react to BomItem lifecycle events.
pub trait BomItemEventHandler: EventHandler<BomItemEvent> {}
