//! Domain events for Bom entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Bom;

/// Domain events for Bom — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Bom>)` variant.
pub type BomEvent = CrudEvent<Bom>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Bom events.
pub type BomEventPublisher = Arc<dyn CrudEventPublisher<Bom> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBomEventPublisher = NoOpCrudEventPublisher<Bom>;
