//! Event handler trait for Bom events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BomEvent;

/// Event handler for Bom events.
/// Implement this trait to react to Bom lifecycle events.
pub trait BomEventHandler: EventHandler<BomEvent> {}
