//! Event handler trait for BomByproduct events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BomByproductEvent;

/// Event handler for BomByproduct events.
/// Implement this trait to react to BomByproduct lifecycle events.
pub trait BomByproductEventHandler: EventHandler<BomByproductEvent> {}
