//! Domain events for BomOperation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BomOperation;

/// Domain events for BomOperation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BomOperation>)` variant.
pub type BomOperationEvent = CrudEvent<BomOperation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BomOperation events.
pub type BomOperationEventPublisher = Arc<dyn CrudEventPublisher<BomOperation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBomOperationEventPublisher = NoOpCrudEventPublisher<BomOperation>;
