//! Event handler trait for BomOperation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BomOperationEvent;

/// Event handler for BomOperation events.
/// Implement this trait to react to BomOperation lifecycle events.
pub trait BomOperationEventHandler: EventHandler<BomOperationEvent> {}
