//! Event handler trait for JobCard events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::JobCardEvent;

/// Event handler for JobCard events.
/// Implement this trait to react to JobCard lifecycle events.
pub trait JobCardEventHandler: EventHandler<JobCardEvent> {}
