//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod workstation_events;
pub mod workstation_event_handlers;
pub mod operation_events;
pub mod operation_event_handlers;
pub mod bom_events;
pub mod bom_event_handlers;
pub mod bom_item_events;
pub mod bom_item_event_handlers;
pub mod bom_operation_events;
pub mod bom_operation_event_handlers;
pub mod work_order_events;
pub mod work_order_event_handlers;
pub mod work_order_item_events;
pub mod work_order_item_event_handlers;
pub mod job_card_events;
pub mod job_card_event_handlers;

pub use workstation_events::{WorkstationEvent, WorkstationEventPublisher, NoopWorkstationEventPublisher};
pub use workstation_event_handlers::WorkstationEventHandler;
pub use operation_events::{OperationEvent, OperationEventPublisher, NoopOperationEventPublisher};
pub use operation_event_handlers::OperationEventHandler;
pub use bom_events::{BomEvent, BomEventPublisher, NoopBomEventPublisher};
pub use bom_event_handlers::BomEventHandler;
pub use bom_item_events::{BomItemEvent, BomItemEventPublisher, NoopBomItemEventPublisher};
pub use bom_item_event_handlers::BomItemEventHandler;
pub use bom_operation_events::{BomOperationEvent, BomOperationEventPublisher, NoopBomOperationEventPublisher};
pub use bom_operation_event_handlers::BomOperationEventHandler;
pub use work_order_events::{WorkOrderEvent, WorkOrderEventPublisher, NoopWorkOrderEventPublisher};
pub use work_order_event_handlers::WorkOrderEventHandler;
pub use work_order_item_events::{WorkOrderItemEvent, WorkOrderItemEventPublisher, NoopWorkOrderItemEventPublisher};
pub use work_order_item_event_handlers::WorkOrderItemEventHandler;
pub use job_card_events::{JobCardEvent, JobCardEventPublisher, NoopJobCardEventPublisher};
pub use job_card_event_handlers::JobCardEventHandler;

// <<< CUSTOM
// END CUSTOM
