//! Event handler trait for Operation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OperationEvent;

/// Event handler for Operation events.
/// Implement this trait to react to Operation lifecycle events.
pub trait OperationEventHandler: EventHandler<OperationEvent> {}
