//! Domain events for SubcontractMoLink entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SubcontractMoLink;

/// Domain events for SubcontractMoLink — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SubcontractMoLink>)` variant.
pub type SubcontractMoLinkEvent = CrudEvent<SubcontractMoLink>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SubcontractMoLink events.
pub type SubcontractMoLinkEventPublisher = Arc<dyn CrudEventPublisher<SubcontractMoLink> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubcontractMoLinkEventPublisher = NoOpCrudEventPublisher<SubcontractMoLink>;
