//! Event handler trait for SubcontractMoLink events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubcontractMoLinkEvent;

/// Event handler for SubcontractMoLink events.
/// Implement this trait to react to SubcontractMoLink lifecycle events.
pub trait SubcontractMoLinkEventHandler: EventHandler<SubcontractMoLinkEvent> {}
