//! Event handler trait for UnbuildOrder events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::UnbuildOrderEvent;

/// Event handler for UnbuildOrder events.
/// Implement this trait to react to UnbuildOrder lifecycle events.
pub trait UnbuildOrderEventHandler: EventHandler<UnbuildOrderEvent> {}
