//! Event handler trait for WorkOrder events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WorkOrderEvent;

/// Event handler for WorkOrder events.
/// Implement this trait to react to WorkOrder lifecycle events.
pub trait WorkOrderEventHandler: EventHandler<WorkOrderEvent> {}
