//! Event handler trait for Workstation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WorkstationEvent;

/// Event handler for Workstation events.
/// Implement this trait to react to Workstation lifecycle events.
pub trait WorkstationEventHandler: EventHandler<WorkstationEvent> {}
