//! Domain events for WorkstationLoss entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WorkstationLoss;

/// Domain events for WorkstationLoss — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WorkstationLoss>)` variant.
pub type WorkstationLossEvent = CrudEvent<WorkstationLoss>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WorkstationLoss events.
pub type WorkstationLossEventPublisher = Arc<dyn CrudEventPublisher<WorkstationLoss> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWorkstationLossEventPublisher = NoOpCrudEventPublisher<WorkstationLoss>;
