//! Domain events for WorkOrderItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WorkOrderItem;

/// Domain events for WorkOrderItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WorkOrderItem>)` variant.
pub type WorkOrderItemEvent = CrudEvent<WorkOrderItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WorkOrderItem events.
pub type WorkOrderItemEventPublisher = Arc<dyn CrudEventPublisher<WorkOrderItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWorkOrderItemEventPublisher = NoOpCrudEventPublisher<WorkOrderItem>;
