//! Event handler trait for WorkOrderItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WorkOrderItemEvent;

/// Event handler for WorkOrderItem events.
/// Implement this trait to react to WorkOrderItem lifecycle events.
pub trait WorkOrderItemEventHandler: EventHandler<WorkOrderItemEvent> {}
