//! Domain events for WorkOrder entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WorkOrder;

/// Domain events for WorkOrder — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WorkOrder>)` variant.
pub type WorkOrderEvent = CrudEvent<WorkOrder>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WorkOrder events.
pub type WorkOrderEventPublisher = Arc<dyn CrudEventPublisher<WorkOrder> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWorkOrderEventPublisher = NoOpCrudEventPublisher<WorkOrder>;
