//! Domain events for Workstation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Workstation;

/// Domain events for Workstation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Workstation>)` variant.
pub type WorkstationEvent = CrudEvent<Workstation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Workstation events.
pub type WorkstationEventPublisher = Arc<dyn CrudEventPublisher<Workstation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWorkstationEventPublisher = NoOpCrudEventPublisher<Workstation>;
