//! Event subscriber type aliases for Manufacturing module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::WorkstationEvent;
use crate::domain::event::OperationEvent;
use crate::domain::event::BomEvent;
use crate::domain::event::BomItemEvent;
use crate::domain::event::BomOperationEvent;
use crate::domain::event::WorkOrderEvent;
use crate::domain::event::WorkOrderItemEvent;
use crate::domain::event::JobCardEvent;

/// Subscriber for Workstation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type WorkstationEventSubscriber = GenericEventSubscriber<WorkstationEvent>;

/// Subscriber for Operation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OperationEventSubscriber = GenericEventSubscriber<OperationEvent>;

/// Subscriber for Bom events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BomEventSubscriber = GenericEventSubscriber<BomEvent>;

/// Subscriber for BomItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BomItemEventSubscriber = GenericEventSubscriber<BomItemEvent>;

/// Subscriber for BomOperation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BomOperationEventSubscriber = GenericEventSubscriber<BomOperationEvent>;

/// Subscriber for WorkOrder events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type WorkOrderEventSubscriber = GenericEventSubscriber<WorkOrderEvent>;

/// Subscriber for WorkOrderItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type WorkOrderItemEventSubscriber = GenericEventSubscriber<WorkOrderItemEvent>;

/// Subscriber for JobCard events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type JobCardEventSubscriber = GenericEventSubscriber<JobCardEvent>;

// <<< CUSTOM
// END CUSTOM
