//! Manufacturing Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::WorkstationEventSubscriber;
pub use handlers::OperationEventSubscriber;
pub use handlers::BomEventSubscriber;
pub use handlers::BomItemEventSubscriber;
pub use handlers::BomOperationEventSubscriber;
pub use handlers::WorkOrderEventSubscriber;
pub use handlers::WorkOrderItemEventSubscriber;
pub use handlers::JobCardEventSubscriber;
