//! BomOperation seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial BomOperation data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BOMOPERATION SEEDER
// ============================================================================

/// Seeder for bom_operation
pub struct SeedBomOperationSeeder;

impl SeedBomOperationSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBomOperationSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBomOperationSeeder {
    fn name(&self) -> &'static str {
        "SeedBomOperationSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if manufacturing.bom_operations table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM manufacturing.bom_operations")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/bom_operation_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM manufacturing.bom_operations")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

