//! BomByproduct seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial BomByproduct data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BOMBYPRODUCT SEEDER
// ============================================================================

/// Seeder for bom_byproduct
pub struct SeedBomByproductSeeder;

impl SeedBomByproductSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBomByproductSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBomByproductSeeder {
    fn name(&self) -> &'static str {
        "SeedBomByproductSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if manufacturing.bom_byproducts table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM manufacturing.bom_byproducts")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/bom_byproduct_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM manufacturing.bom_byproducts")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
