//! CategoryCostingDefaults seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CategoryCostingDefaults data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CATEGORYCOSTINGDEFAULTS SEEDER
// ============================================================================

/// Seeder for category_costing_defaults
pub struct SeedCategoryCostingDefaultsSeeder;

impl SeedCategoryCostingDefaultsSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCategoryCostingDefaultsSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCategoryCostingDefaultsSeeder {
    fn name(&self) -> &'static str {
        "SeedCategoryCostingDefaultsSeeder"
    }

    fn order(&self) -> i32 {
        10
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if manufacturing.category_costing_defaults table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM manufacturing.category_costing_defaults")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/category_costing_defaults_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM manufacturing.category_costing_defaults")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
