//! Database seeders for the manufacturing module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod workstation_seeder;
mod operation_seeder;
mod bom_seeder;
mod bom_item_seeder;
mod bom_operation_seeder;
mod work_order_seeder;
mod work_order_item_seeder;
mod job_card_seeder;

pub use workstation_seeder::SeedWorkstationSeeder;
pub use operation_seeder::SeedOperationSeeder;
pub use bom_seeder::SeedBomSeeder;
pub use bom_item_seeder::SeedBomItemSeeder;
pub use bom_operation_seeder::SeedBomOperationSeeder;
pub use work_order_seeder::SeedWorkOrderSeeder;
pub use work_order_item_seeder::SeedWorkOrderItemSeeder;
pub use job_card_seeder::SeedJobCardSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here.
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
