//! SubcontractMoLink seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SubcontractMoLink data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SUBCONTRACTMOLINK SEEDER
// ============================================================================

/// Seeder for subcontract_mo_link
pub struct SeedSubcontractMoLinkSeeder;

impl SeedSubcontractMoLinkSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSubcontractMoLinkSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSubcontractMoLinkSeeder {
    fn name(&self) -> &'static str {
        "SeedSubcontractMoLinkSeeder"
    }

    fn order(&self) -> i32 {
        18
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if manufacturing.subcontract_mo_links table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM manufacturing.subcontract_mo_links")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/subcontract_mo_link_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM manufacturing.subcontract_mo_links")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
