//! Repository trait for BomByproduct aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BomByproduct aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::BomByproduct;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomByproductPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BomByproductPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BomByproductPaginatedResult {
    pub data: Vec<BomByproduct>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomByproductFilter {
    pub company_id: Option<Uuid>,
    pub bom_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub product_category_id: Option<Uuid>,
}

impl BomByproductFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bom_id.is_some() || self.item_id.is_some() || self.product_category_id.is_some()
    }
}

/// Repository trait for BomByproduct aggregate
///
/// This trait defines the persistence contract for BomByproduct entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BomByproductRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bom_byproduct entity
    async fn save(&self, entity: &BomByproduct) -> Result<BomByproduct>;

    /// Find bom_byproduct by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BomByproduct>>;

    /// Find all bom_byproduct entities
    async fn find_all(&self) -> Result<Vec<BomByproduct>>;

    /// Update bom_byproduct by ID
    async fn update(&self, id: &str, entity: &BomByproduct) -> Result<Option<BomByproduct>>;

    /// Delete bom_byproduct by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bom_byproduct with pagination
    async fn list(&self, params: BomByproductPaginationParams) -> Result<BomByproductPaginatedResult>;

    /// List bom_byproduct with pagination and filters
    async fn list_with_filters(&self, params: BomByproductPaginationParams, filters: BomByproductFilter) -> Result<BomByproductPaginatedResult>;

    /// Count all bom_byproduct entities
    async fn count(&self) -> Result<u64>;

    /// Count bom_byproduct entities matching filters
    async fn count_with_filters(&self, filters: BomByproductFilter) -> Result<u64>;

    /// Check if bom_byproduct exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bom_byproduct by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bom_byproduct by ID
    async fn restore(&self, id: &str) -> Result<Option<BomByproduct>>;

    /// List soft-deleted bom_byproduct entities
    async fn list_deleted(&self, params: BomByproductPaginationParams) -> Result<BomByproductPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bom_byproduct entities
    async fn bulk_save(&self, entities: &[BomByproduct]) -> Result<Vec<BomByproduct>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
