//! Repository trait for BomSubcontractor aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BomSubcontractor aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::BomSubcontractor;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomSubcontractorPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BomSubcontractorPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BomSubcontractorPaginatedResult {
    pub data: Vec<BomSubcontractor>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomSubcontractorFilter {
    pub company_id: Option<Uuid>,
    pub bom_id: Option<Uuid>,
    pub partner_id: Option<Uuid>,
}

impl BomSubcontractorFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bom_id.is_some() || self.partner_id.is_some()
    }
}

/// Repository trait for BomSubcontractor aggregate
///
/// This trait defines the persistence contract for BomSubcontractor entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BomSubcontractorRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bom_subcontractor entity
    async fn save(&self, entity: &BomSubcontractor) -> Result<BomSubcontractor>;

    /// Find bom_subcontractor by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BomSubcontractor>>;

    /// Find all bom_subcontractor entities
    async fn find_all(&self) -> Result<Vec<BomSubcontractor>>;

    /// Update bom_subcontractor by ID
    async fn update(&self, id: &str, entity: &BomSubcontractor) -> Result<Option<BomSubcontractor>>;

    /// Delete bom_subcontractor by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bom_subcontractor with pagination
    async fn list(&self, params: BomSubcontractorPaginationParams) -> Result<BomSubcontractorPaginatedResult>;

    /// List bom_subcontractor with pagination and filters
    async fn list_with_filters(&self, params: BomSubcontractorPaginationParams, filters: BomSubcontractorFilter) -> Result<BomSubcontractorPaginatedResult>;

    /// Count all bom_subcontractor entities
    async fn count(&self) -> Result<u64>;

    /// Count bom_subcontractor entities matching filters
    async fn count_with_filters(&self, filters: BomSubcontractorFilter) -> Result<u64>;

    /// Check if bom_subcontractor exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bom_subcontractor by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bom_subcontractor by ID
    async fn restore(&self, id: &str) -> Result<Option<BomSubcontractor>>;

    /// List soft-deleted bom_subcontractor entities
    async fn list_deleted(&self, params: BomSubcontractorPaginationParams) -> Result<BomSubcontractorPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bom_subcontractor entities
    async fn bulk_save(&self, entities: &[BomSubcontractor]) -> Result<Vec<BomSubcontractor>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
