//! Repository trait for BomOperation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BomOperation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::BomOperation;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomOperationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BomOperationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BomOperationPaginatedResult {
    pub data: Vec<BomOperation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomOperationFilter {
    pub company_id: Option<Uuid>,
    pub bom_id: Option<Uuid>,
    pub operation_id: Option<Uuid>,
    pub workstation_id: Option<Uuid>,
}

impl BomOperationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bom_id.is_some() || self.operation_id.is_some() || self.workstation_id.is_some()
    }
}

/// Repository trait for BomOperation aggregate
///
/// This trait defines the persistence contract for BomOperation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BomOperationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bom_operation entity
    async fn save(&self, entity: &BomOperation) -> Result<BomOperation>;

    /// Find bom_operation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BomOperation>>;

    /// Find all bom_operation entities
    async fn find_all(&self) -> Result<Vec<BomOperation>>;

    /// Update bom_operation by ID
    async fn update(&self, id: &str, entity: &BomOperation) -> Result<Option<BomOperation>>;

    /// Delete bom_operation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bom_operation with pagination
    async fn list(&self, params: BomOperationPaginationParams) -> Result<BomOperationPaginatedResult>;

    /// List bom_operation with pagination and filters
    async fn list_with_filters(&self, params: BomOperationPaginationParams, filters: BomOperationFilter) -> Result<BomOperationPaginatedResult>;

    /// Count all bom_operation entities
    async fn count(&self) -> Result<u64>;

    /// Count bom_operation entities matching filters
    async fn count_with_filters(&self, filters: BomOperationFilter) -> Result<u64>;

    /// Check if bom_operation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bom_operation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bom_operation by ID
    async fn restore(&self, id: &str) -> Result<Option<BomOperation>>;

    /// List soft-deleted bom_operation entities
    async fn list_deleted(&self, params: BomOperationPaginationParams) -> Result<BomOperationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bom_operation entities
    async fn bulk_save(&self, entities: &[BomOperation]) -> Result<Vec<BomOperation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
