//! Repository trait for BomItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BomItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::BomItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BomItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BomItemPaginatedResult {
    pub data: Vec<BomItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BomItemFilter {
    pub company_id: Option<Uuid>,
    pub bom_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub is_phantom: Option<bool>,
}

impl BomItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bom_id.is_some() || self.item_id.is_some() || self.is_phantom.is_some()
    }
}

/// Repository trait for BomItem aggregate
///
/// This trait defines the persistence contract for BomItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BomItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bom_item entity
    async fn save(&self, entity: &BomItem) -> Result<BomItem>;

    /// Find bom_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BomItem>>;

    /// Find all bom_item entities
    async fn find_all(&self) -> Result<Vec<BomItem>>;

    /// Update bom_item by ID
    async fn update(&self, id: &str, entity: &BomItem) -> Result<Option<BomItem>>;

    /// Delete bom_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bom_item with pagination
    async fn list(&self, params: BomItemPaginationParams) -> Result<BomItemPaginatedResult>;

    /// List bom_item with pagination and filters
    async fn list_with_filters(&self, params: BomItemPaginationParams, filters: BomItemFilter) -> Result<BomItemPaginatedResult>;

    /// Count all bom_item entities
    async fn count(&self) -> Result<u64>;

    /// Count bom_item entities matching filters
    async fn count_with_filters(&self, filters: BomItemFilter) -> Result<u64>;

    /// Check if bom_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bom_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bom_item by ID
    async fn restore(&self, id: &str) -> Result<Option<BomItem>>;

    /// List soft-deleted bom_item entities
    async fn list_deleted(&self, params: BomItemPaginationParams) -> Result<BomItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bom_item entities
    async fn bulk_save(&self, entities: &[BomItem]) -> Result<Vec<BomItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
