//! Repository trait for CategoryCostingDefaults aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CategoryCostingDefaults aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CategoryCostingDefaults;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CategoryCostingDefaultsPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CategoryCostingDefaultsPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CategoryCostingDefaultsPaginatedResult {
    pub data: Vec<CategoryCostingDefaults>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CategoryCostingDefaultsFilter {
    pub company_id: Option<Uuid>,
    pub product_category_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
    pub subcontract_interim_account_id: Option<Uuid>,
    pub cost_variance_account_id: Option<Uuid>,
    pub inventory_loss_account_id: Option<Uuid>,
    pub repair_expense_account_id: Option<Uuid>,
}

impl CategoryCostingDefaultsFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.product_category_id.is_some() || self.wip_account_id.is_some() || self.fg_account_id.is_some() || self.raw_material_account_id.is_some() || self.conversion_cost_account_id.is_some() || self.subcontract_interim_account_id.is_some() || self.cost_variance_account_id.is_some() || self.inventory_loss_account_id.is_some() || self.repair_expense_account_id.is_some()
    }
}

/// Repository trait for CategoryCostingDefaults aggregate
///
/// This trait defines the persistence contract for CategoryCostingDefaults entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CategoryCostingDefaultsRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new category_costing_defaults entity
    async fn save(&self, entity: &CategoryCostingDefaults) -> Result<CategoryCostingDefaults>;

    /// Find category_costing_defaults by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CategoryCostingDefaults>>;

    /// Find all category_costing_defaults entities
    async fn find_all(&self) -> Result<Vec<CategoryCostingDefaults>>;

    /// Update category_costing_defaults by ID
    async fn update(&self, id: &str, entity: &CategoryCostingDefaults) -> Result<Option<CategoryCostingDefaults>>;

    /// Delete category_costing_defaults by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List category_costing_defaults with pagination
    async fn list(&self, params: CategoryCostingDefaultsPaginationParams) -> Result<CategoryCostingDefaultsPaginatedResult>;

    /// List category_costing_defaults with pagination and filters
    async fn list_with_filters(&self, params: CategoryCostingDefaultsPaginationParams, filters: CategoryCostingDefaultsFilter) -> Result<CategoryCostingDefaultsPaginatedResult>;

    /// Count all category_costing_defaults entities
    async fn count(&self) -> Result<u64>;

    /// Count category_costing_defaults entities matching filters
    async fn count_with_filters(&self, filters: CategoryCostingDefaultsFilter) -> Result<u64>;

    /// Check if category_costing_defaults exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete category_costing_defaults by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted category_costing_defaults by ID
    async fn restore(&self, id: &str) -> Result<Option<CategoryCostingDefaults>>;

    /// List soft-deleted category_costing_defaults entities
    async fn list_deleted(&self, params: CategoryCostingDefaultsPaginationParams) -> Result<CategoryCostingDefaultsPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save category_costing_defaults entities
    async fn bulk_save(&self, entities: &[CategoryCostingDefaults]) -> Result<Vec<CategoryCostingDefaults>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
