//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod workstation_repository;
pub mod operation_repository;
pub mod bom_repository;
pub mod bom_item_repository;
pub mod bom_operation_repository;
pub mod work_order_repository;
pub mod work_order_item_repository;
pub mod job_card_repository;

// Re-exports
pub use workstation_repository::{
    WorkstationRepository,
    WorkstationPaginationParams,
    WorkstationPaginatedResult,
    WorkstationFilter,
};
pub use operation_repository::{
    OperationRepository,
    OperationPaginationParams,
    OperationPaginatedResult,
    OperationFilter,
};
pub use bom_repository::{
    BomRepository,
    BomPaginationParams,
    BomPaginatedResult,
    BomFilter,
};
pub use bom_item_repository::{
    BomItemRepository,
    BomItemPaginationParams,
    BomItemPaginatedResult,
    BomItemFilter,
};
pub use bom_operation_repository::{
    BomOperationRepository,
    BomOperationPaginationParams,
    BomOperationPaginatedResult,
    BomOperationFilter,
};
pub use work_order_repository::{
    WorkOrderRepository,
    WorkOrderPaginationParams,
    WorkOrderPaginatedResult,
    WorkOrderFilter,
};
pub use work_order_item_repository::{
    WorkOrderItemRepository,
    WorkOrderItemPaginationParams,
    WorkOrderItemPaginatedResult,
    WorkOrderItemFilter,
};
pub use job_card_repository::{
    JobCardRepository,
    JobCardPaginationParams,
    JobCardPaginatedResult,
    JobCardFilter,
};
