//! Repository trait for Operation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Operation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Operation;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OperationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OperationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OperationPaginatedResult {
    pub data: Vec<Operation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OperationFilter {
    pub company_id: Option<Uuid>,
    pub operation_name: Option<String>,
    pub default_workstation_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl OperationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.operation_name.is_some() || self.default_workstation_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for Operation aggregate
///
/// This trait defines the persistence contract for Operation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OperationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new operation entity
    async fn save(&self, entity: &Operation) -> Result<Operation>;

    /// Find operation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Operation>>;

    /// Find all operation entities
    async fn find_all(&self) -> Result<Vec<Operation>>;

    /// Update operation by ID
    async fn update(&self, id: &str, entity: &Operation) -> Result<Option<Operation>>;

    /// Delete operation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List operation with pagination
    async fn list(&self, params: OperationPaginationParams) -> Result<OperationPaginatedResult>;

    /// List operation with pagination and filters
    async fn list_with_filters(&self, params: OperationPaginationParams, filters: OperationFilter) -> Result<OperationPaginatedResult>;

    /// Count all operation entities
    async fn count(&self) -> Result<u64>;

    /// Count operation entities matching filters
    async fn count_with_filters(&self, filters: OperationFilter) -> Result<u64>;

    /// Check if operation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete operation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted operation by ID
    async fn restore(&self, id: &str) -> Result<Option<Operation>>;

    /// List soft-deleted operation entities
    async fn list_deleted(&self, params: OperationPaginationParams) -> Result<OperationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save operation entities
    async fn bulk_save(&self, entities: &[Operation]) -> Result<Vec<Operation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
