//! Repository trait for SubcontractMoLink aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SubcontractMoLink aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SubcontractMoLink;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubcontractMoLinkPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubcontractMoLinkPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubcontractMoLinkPaginatedResult {
    pub data: Vec<SubcontractMoLink>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubcontractMoLinkFilter {
    pub purchase_order_id: Option<Uuid>,
    pub work_order_id: Option<Uuid>,
}

impl SubcontractMoLinkFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.purchase_order_id.is_some() || self.work_order_id.is_some()
    }
}

/// Repository trait for SubcontractMoLink aggregate
///
/// This trait defines the persistence contract for SubcontractMoLink entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubcontractMoLinkRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subcontract_mo_link entity
    async fn save(&self, entity: &SubcontractMoLink) -> Result<SubcontractMoLink>;

    /// Find subcontract_mo_link by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SubcontractMoLink>>;

    /// Find all subcontract_mo_link entities
    async fn find_all(&self) -> Result<Vec<SubcontractMoLink>>;

    /// Update subcontract_mo_link by ID
    async fn update(&self, id: &str, entity: &SubcontractMoLink) -> Result<Option<SubcontractMoLink>>;

    /// Delete subcontract_mo_link by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subcontract_mo_link with pagination
    async fn list(&self, params: SubcontractMoLinkPaginationParams) -> Result<SubcontractMoLinkPaginatedResult>;

    /// List subcontract_mo_link with pagination and filters
    async fn list_with_filters(&self, params: SubcontractMoLinkPaginationParams, filters: SubcontractMoLinkFilter) -> Result<SubcontractMoLinkPaginatedResult>;

    /// Count all subcontract_mo_link entities
    async fn count(&self) -> Result<u64>;

    /// Count subcontract_mo_link entities matching filters
    async fn count_with_filters(&self, filters: SubcontractMoLinkFilter) -> Result<u64>;

    /// Check if subcontract_mo_link exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subcontract_mo_link by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subcontract_mo_link by ID
    async fn restore(&self, id: &str) -> Result<Option<SubcontractMoLink>>;

    /// List soft-deleted subcontract_mo_link entities
    async fn list_deleted(&self, params: SubcontractMoLinkPaginationParams) -> Result<SubcontractMoLinkPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subcontract_mo_link entities
    async fn bulk_save(&self, entities: &[SubcontractMoLink]) -> Result<Vec<SubcontractMoLink>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
