//! Repository trait for UnbuildOrder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the UnbuildOrder aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{UnbuildOrder, UnbuildStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct UnbuildOrderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl UnbuildOrderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct UnbuildOrderPaginatedResult {
    pub data: Vec<UnbuildOrder>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct UnbuildOrderFilter {
    pub unbuild_number: Option<String>,
    pub work_order_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub status: Option<UnbuildStatus>,
}

impl UnbuildOrderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.unbuild_number.is_some() || self.work_order_id.is_some() || self.item_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for UnbuildOrder aggregate
///
/// This trait defines the persistence contract for UnbuildOrder entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait UnbuildOrderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new unbuild_order entity
    async fn save(&self, entity: &UnbuildOrder) -> Result<UnbuildOrder>;

    /// Find unbuild_order by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<UnbuildOrder>>;

    /// Find all unbuild_order entities
    async fn find_all(&self) -> Result<Vec<UnbuildOrder>>;

    /// Update unbuild_order by ID
    async fn update(&self, id: &str, entity: &UnbuildOrder) -> Result<Option<UnbuildOrder>>;

    /// Delete unbuild_order by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List unbuild_order with pagination
    async fn list(&self, params: UnbuildOrderPaginationParams) -> Result<UnbuildOrderPaginatedResult>;

    /// List unbuild_order with pagination and filters
    async fn list_with_filters(&self, params: UnbuildOrderPaginationParams, filters: UnbuildOrderFilter) -> Result<UnbuildOrderPaginatedResult>;

    /// Count all unbuild_order entities
    async fn count(&self) -> Result<u64>;

    /// Count unbuild_order entities matching filters
    async fn count_with_filters(&self, filters: UnbuildOrderFilter) -> Result<u64>;

    /// Check if unbuild_order exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete unbuild_order by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted unbuild_order by ID
    async fn restore(&self, id: &str) -> Result<Option<UnbuildOrder>>;

    /// List soft-deleted unbuild_order entities
    async fn list_deleted(&self, params: UnbuildOrderPaginationParams) -> Result<UnbuildOrderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save unbuild_order entities
    async fn bulk_save(&self, entities: &[UnbuildOrder]) -> Result<Vec<UnbuildOrder>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
