//! Repository trait for WorkstationLoss aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WorkstationLoss aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{WorkstationLoss, LossType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationLossPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WorkstationLossPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WorkstationLossPaginatedResult {
    pub data: Vec<WorkstationLoss>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationLossFilter {
    pub name: Option<String>,
    pub loss_type: Option<LossType>,
}

impl WorkstationLossFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.loss_type.is_some()
    }
}

/// Repository trait for WorkstationLoss aggregate
///
/// This trait defines the persistence contract for WorkstationLoss entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WorkstationLossRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new workstation_loss entity
    async fn save(&self, entity: &WorkstationLoss) -> Result<WorkstationLoss>;

    /// Find workstation_loss by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WorkstationLoss>>;

    /// Find all workstation_loss entities
    async fn find_all(&self) -> Result<Vec<WorkstationLoss>>;

    /// Update workstation_loss by ID
    async fn update(&self, id: &str, entity: &WorkstationLoss) -> Result<Option<WorkstationLoss>>;

    /// Delete workstation_loss by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List workstation_loss with pagination
    async fn list(&self, params: WorkstationLossPaginationParams) -> Result<WorkstationLossPaginatedResult>;

    /// List workstation_loss with pagination and filters
    async fn list_with_filters(&self, params: WorkstationLossPaginationParams, filters: WorkstationLossFilter) -> Result<WorkstationLossPaginatedResult>;

    /// Count all workstation_loss entities
    async fn count(&self) -> Result<u64>;

    /// Count workstation_loss entities matching filters
    async fn count_with_filters(&self, filters: WorkstationLossFilter) -> Result<u64>;

    /// Check if workstation_loss exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete workstation_loss by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted workstation_loss by ID
    async fn restore(&self, id: &str) -> Result<Option<WorkstationLoss>>;

    /// List soft-deleted workstation_loss entities
    async fn list_deleted(&self, params: WorkstationLossPaginationParams) -> Result<WorkstationLossPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save workstation_loss entities
    async fn bulk_save(&self, entities: &[WorkstationLoss]) -> Result<Vec<WorkstationLoss>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
