//! Repository trait for Workstation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Workstation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Workstation;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WorkstationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WorkstationPaginatedResult {
    pub data: Vec<Workstation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationFilter {
    pub company_id: Option<Uuid>,
    pub workstation_name: Option<String>,
    pub is_active: Option<bool>,
}

impl WorkstationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.workstation_name.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for Workstation aggregate
///
/// This trait defines the persistence contract for Workstation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WorkstationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new workstation entity
    async fn save(&self, entity: &Workstation) -> Result<Workstation>;

    /// Find workstation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Workstation>>;

    /// Find all workstation entities
    async fn find_all(&self) -> Result<Vec<Workstation>>;

    /// Update workstation by ID
    async fn update(&self, id: &str, entity: &Workstation) -> Result<Option<Workstation>>;

    /// Delete workstation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List workstation with pagination
    async fn list(&self, params: WorkstationPaginationParams) -> Result<WorkstationPaginatedResult>;

    /// List workstation with pagination and filters
    async fn list_with_filters(&self, params: WorkstationPaginationParams, filters: WorkstationFilter) -> Result<WorkstationPaginatedResult>;

    /// Count all workstation entities
    async fn count(&self) -> Result<u64>;

    /// Count workstation entities matching filters
    async fn count_with_filters(&self, filters: WorkstationFilter) -> Result<u64>;

    /// Check if workstation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete workstation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted workstation by ID
    async fn restore(&self, id: &str) -> Result<Option<Workstation>>;

    /// List soft-deleted workstation entities
    async fn list_deleted(&self, params: WorkstationPaginationParams) -> Result<WorkstationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save workstation entities
    async fn bulk_save(&self, entities: &[Workstation]) -> Result<Vec<Workstation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
