//! Repository trait for WorkOrder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WorkOrder aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{WorkOrder, WorkOrderStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkOrderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WorkOrderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WorkOrderPaginatedResult {
    pub data: Vec<WorkOrder>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkOrderFilter {
    pub company_id: Option<Uuid>,
    pub work_order_number: Option<String>,
    pub item_id: Option<Uuid>,
    pub bom_id: Option<Uuid>,
    pub status: Option<WorkOrderStatus>,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
}

impl WorkOrderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.work_order_number.is_some() || self.item_id.is_some() || self.bom_id.is_some() || self.status.is_some() || self.wip_warehouse_id.is_some() || self.fg_warehouse_id.is_some() || self.wip_account_id.is_some() || self.fg_account_id.is_some() || self.raw_material_account_id.is_some() || self.conversion_cost_account_id.is_some()
    }
}

/// Repository trait for WorkOrder aggregate
///
/// This trait defines the persistence contract for WorkOrder entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WorkOrderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new work_order entity
    async fn save(&self, entity: &WorkOrder) -> Result<WorkOrder>;

    /// Find work_order by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WorkOrder>>;

    /// Find all work_order entities
    async fn find_all(&self) -> Result<Vec<WorkOrder>>;

    /// Update work_order by ID
    async fn update(&self, id: &str, entity: &WorkOrder) -> Result<Option<WorkOrder>>;

    /// Delete work_order by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List work_order with pagination
    async fn list(&self, params: WorkOrderPaginationParams) -> Result<WorkOrderPaginatedResult>;

    /// List work_order with pagination and filters
    async fn list_with_filters(&self, params: WorkOrderPaginationParams, filters: WorkOrderFilter) -> Result<WorkOrderPaginatedResult>;

    /// Count all work_order entities
    async fn count(&self) -> Result<u64>;

    /// Count work_order entities matching filters
    async fn count_with_filters(&self, filters: WorkOrderFilter) -> Result<u64>;

    /// Check if work_order exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete work_order by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted work_order by ID
    async fn restore(&self, id: &str) -> Result<Option<WorkOrder>>;

    /// List soft-deleted work_order entities
    async fn list_deleted(&self, params: WorkOrderPaginationParams) -> Result<WorkOrderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save work_order entities
    async fn bulk_save(&self, entities: &[WorkOrder]) -> Result<Vec<WorkOrder>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
