//! Repository trait for WorkstationProductivity aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WorkstationProductivity aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::WorkstationProductivity;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationProductivityPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WorkstationProductivityPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WorkstationProductivityPaginatedResult {
    pub data: Vec<WorkstationProductivity>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WorkstationProductivityFilter {
    pub workstation_id: Option<Uuid>,
    pub job_card_id: Option<Uuid>,
    pub loss_id: Option<Uuid>,
    pub description: Option<String>,
}

impl WorkstationProductivityFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.workstation_id.is_some() || self.job_card_id.is_some() || self.loss_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for WorkstationProductivity aggregate
///
/// This trait defines the persistence contract for WorkstationProductivity entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WorkstationProductivityRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new workstation_productivity entity
    async fn save(&self, entity: &WorkstationProductivity) -> Result<WorkstationProductivity>;

    /// Find workstation_productivity by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WorkstationProductivity>>;

    /// Find all workstation_productivity entities
    async fn find_all(&self) -> Result<Vec<WorkstationProductivity>>;

    /// Update workstation_productivity by ID
    async fn update(&self, id: &str, entity: &WorkstationProductivity) -> Result<Option<WorkstationProductivity>>;

    /// Delete workstation_productivity by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List workstation_productivity with pagination
    async fn list(&self, params: WorkstationProductivityPaginationParams) -> Result<WorkstationProductivityPaginatedResult>;

    /// List workstation_productivity with pagination and filters
    async fn list_with_filters(&self, params: WorkstationProductivityPaginationParams, filters: WorkstationProductivityFilter) -> Result<WorkstationProductivityPaginatedResult>;

    /// Count all workstation_productivity entities
    async fn count(&self) -> Result<u64>;

    /// Count workstation_productivity entities matching filters
    async fn count_with_filters(&self, filters: WorkstationProductivityFilter) -> Result<u64>;

    /// Check if workstation_productivity exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete workstation_productivity by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted workstation_productivity by ID
    async fn restore(&self, id: &str) -> Result<Option<WorkstationProductivity>>;

    /// List soft-deleted workstation_productivity entities
    async fn list_deleted(&self, params: WorkstationProductivityPaginationParams) -> Result<WorkstationProductivityPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save workstation_productivity entities
    async fn bulk_save(&self, entities: &[WorkstationProductivity]) -> Result<Vec<WorkstationProductivity>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
