//! Repository for BomItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written BomItem SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::BomItem;

/// Table name for BomItem entities
pub const TABLE_NAME: &str = "manufacturing.bom_items";

/// Repository for BomItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BomItemRepository(
    backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BomItemRepository {
    type Target = backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BomItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a BOM-component insert writes. `amount` is already computed server-side by the
/// write service (`money(quantity * rate)`), not re-derived here.
pub struct NewBomItemRow {
    pub id: Uuid,
    pub bom_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub amount: Decimal,
    pub is_phantom: bool,
}

/// One BOM component as the explosion reads it. `is_phantom` decides the branch: a phantom is never
/// issued, it is exploded through to its own BOM's components.
pub struct BomComponentRow {
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub is_phantom: bool,
}

/// Hand-written BomItem SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl BomItemRepository {
    /// Insert one BOM component.
    ///
    /// Takes the CALLER'S connection so the component commits in the SAME transaction as its header.
    /// The caller binds the company on that connection (`bind_company_on`) before calling — don't
    /// re-bind.
    pub async fn insert_component(
        &self,
        conn: &mut sqlx::PgConnection,
        c: &NewBomItemRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO manufacturing.bom_items (id, bom_id, item_id, quantity, rate, amount, is_phantom)
               VALUES ($1,$2,$3,$4,$5,$6,$7)"#,
        )
        .bind(c.id).bind(c.bom_id).bind(c.item_id).bind(c.quantity).bind(c.rate)
        .bind(c.amount).bind(c.is_phantom)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a BOM's components for the explosion.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_all_rows_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` — the
    /// company is on the parameter — so the explosion stays fenced even when driven by a non-request
    /// caller (job / event subscriber).
    pub async fn list_components(
        &self,
        pool: &PgPool,
        bom_id: Uuid,
    ) -> Result<Vec<BomComponentRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT item_id, quantity, rate, is_phantom FROM manufacturing.bom_items WHERE bom_id=$1"#,
            )
            .bind(bom_id),
        ).await?;
        Ok(rows.iter().map(|r| BomComponentRow {
            item_id: r.get("item_id"),
            quantity: r.get("quantity"),
            rate: r.get("rate"),
            is_phantom: r.get("is_phantom"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(BomItemRepository, BomItem, soft_delete);
