//! Repository for BomItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BomItem;

/// Table name for BomItem entities
pub const TABLE_NAME: &str = "manufacturing.bom_items";

/// Repository for BomItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BomItemRepository(
    backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BomItemRepository {
    type Target = backbone_orm::GenericCrudRepository<BomItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BomItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BomItemRepository, BomItem, soft_delete);
