//! Repository for Bom entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written Bom header SQL statement (4-layer rule: services
//! orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Bom, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Bom;

/// Table name for Bom entities
pub const TABLE_NAME: &str = "manufacturing.boms";

/// Repository for Bom entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BomRepository(
    backbone_orm::GenericCrudRepository<Bom, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BomRepository {
    type Target = backbone_orm::GenericCrudRepository<Bom, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BomRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a BOM-header insert writes.
///
/// Mirrors the raw column shape rather than the `Bom` entity: the three cost columns are already
/// rolled up server-side by the write service, and `currency` / `status` / `is_default` /
/// `version` / `bom_type` are pinned by the statement (`'IDR'`, `'active'`, `false`, `1`,
/// `'normal'`) rather than passed. `company_id` is nullable: a NULL company is shared master
/// data, visible to every company session (the shared_blank fence, ADR-0014).
pub struct NewBomRow<'a> {
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    pub item_id: Uuid,
    pub bom_code: &'a str,
    pub quantity: Decimal,
    pub uom: Option<&'a str>,
    pub raw_material_cost: Decimal,
    pub operating_cost: Decimal,
    pub total_cost: Decimal,
}

/// Hand-written Bom SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl BomRepository {
    /// Insert a BOM header.
    ///
    /// Takes the CALLER'S connection so the header, its components and its operations commit as ONE
    /// unit. The caller binds the company on that connection (`bind_company_on`) before calling —
    /// don't re-bind here. The explicit `company_id` bind stays as defense-in-depth behind the RLS
    /// fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate BOM code into a domain error.
    pub async fn insert_bom(
        &self,
        conn: &mut sqlx::PgConnection,
        b: &NewBomRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO manufacturing.boms
                 (id, company_id, item_id, bom_code, quantity, uom, currency,
                  raw_material_cost, operating_cost, total_cost, status, is_default,
                  version, bom_type)
               VALUES ($1,$2,$3,$4,$5,$6,'IDR',$7,$8,$9,'active',false,1,'normal'::bom_type)"#,
        )
        .bind(b.id).bind(b.company_id).bind(b.item_id).bind(b.bom_code).bind(b.quantity)
        .bind(b.uom).bind(b.raw_material_cost).bind(b.operating_cost).bind(b.total_cost)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a BOM's output quantity — the denominator the explosion prorates each component against.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_scalar_scoped` so the
    /// RLS fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))`
    /// — the company is on the parameter — so the explosion stays fenced even when driven by a
    /// non-request caller (job / event subscriber).
    pub async fn fetch_output_quantity(
        &self,
        pool: &PgPool,
        bom_id: Uuid,
    ) -> Result<Option<Decimal>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT quantity FROM manufacturing.boms WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(bom_id),
        ).await
    }

    /// Read a BOM's owning company (NULL = a shared master-data row). Byproduct authoring
    /// mirrors this onto the child row so a byproduct rides its BoM's fence posture.
    pub async fn fetch_company_id(
        &self,
        pool: &PgPool,
        bom_id: Uuid,
    ) -> Result<Option<Option<Uuid>>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT company_id FROM manufacturing.boms
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(bom_id),
        ).await
    }

    /// Read a BOM's type (normal / kit / subcontract).
    ///
    /// The confirm verb refuses kit and subcontract BoMs LOUDLY: a phantom KIT never gets its own
    /// work order (it explodes through to components at demand time), and a SUBCONTRACT order is
    /// minted only by the subcontract receipt event — hidden and directly in `confirmed`.
    pub async fn fetch_bom_type(
        &self,
        pool: &PgPool,
        bom_id: Uuid,
    ) -> Result<Option<String>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT bom_type::text FROM manufacturing.boms
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(bom_id),
        ).await
    }

    /// Resolve the BOM to explode a phantom component through: its item's active BOM, company-owned
    /// before shared, default first, oldest as the tiebreak (a deterministic pick — the explosion
    /// must not vary run to run).
    ///
    /// The `OR company_id IS NULL` arm is the shared_blank master-data read (ADR-0014): a recipe
    /// authored once as shared master data resolves for every company, while a company-owned BoM of
    /// the same item still wins. Same scoping as [`Self::fetch_output_quantity`].
    pub async fn find_active_bom_for_item(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        item_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM manufacturing.boms
                   WHERE (company_id=$1 OR company_id IS NULL) AND item_id=$2 AND status='active'
                     AND (metadata->>'deleted_at') IS NULL
                   ORDER BY (company_id IS NULL) ASC, is_default DESC,
                            (metadata->>'created_at') ASC LIMIT 1"#,
            )
            .bind(company_id)
            .bind(item_id),
        ).await
    }
}

backbone_core::impl_crud_repository!(BomRepository, Bom, soft_delete);
