//! Repository for CategoryCostingDefaults entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CategoryCostingDefaults, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CategoryCostingDefaults;

/// Table name for CategoryCostingDefaults entities
pub const TABLE_NAME: &str = "manufacturing.category_costing_defaults";

/// Repository for CategoryCostingDefaults entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CategoryCostingDefaultsRepository(
    backbone_orm::GenericCrudRepository<CategoryCostingDefaults, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CategoryCostingDefaultsRepository {
    type Target = backbone_orm::GenericCrudRepository<CategoryCostingDefaults, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CategoryCostingDefaultsRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CategoryCostingDefaultsRepository, CategoryCostingDefaults, soft_delete);
