//! Repository for JobCard entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written JobCard SQL, including the open→completed gate that is the once-only
//! guard on the conversion-cost post (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<JobCard, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::JobCard;

/// Table name for JobCard entities
pub const TABLE_NAME: &str = "manufacturing.job_cards";

/// Repository for JobCard entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JobCardRepository(
    backbone_orm::GenericCrudRepository<JobCard, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for JobCardRepository {
    type Target = backbone_orm::GenericCrudRepository<JobCard, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JobCardRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a job-card insert writes. `operating_cost` is already computed server-side by the
/// write service (`money(total_time_mins / 60 * hour_rate)`), and `status` is not a parameter — the
/// statement pins `'open'::job_card_status` so a new job card can only ever start open.
pub struct NewJobCardRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub work_order_id: Uuid,
    pub operation_id: Uuid,
    pub workstation_id: Uuid,
    pub total_time_mins: Decimal,
    pub hour_rate: Decimal,
    pub operating_cost: Decimal,
}

/// What `complete_job_card` needs: the job card joined to its work order, so the GL accounts and both
/// states are read in ONE round trip. Both statuses are read as `::text` so an unknown state fails a
/// check rather than panicking in a decode.
pub struct JobCardCompletionRow {
    pub company_id: Uuid,
    pub work_order_id: Uuid,
    pub operating_cost: Decimal,
    pub status: String,
    pub wip_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
    pub work_order_number: String,
    pub work_order_status: String,
}

/// Hand-written JobCard SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl JobCardRepository {
    /// Insert an open job card.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company
    /// is on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_open(
        &self,
        pool: &PgPool,
        j: &NewJobCardRow,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO manufacturing.job_cards
                     (id, company_id, work_order_id, operation_id, workstation_id, total_time_mins,
                      hour_rate, operating_cost, status)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'open'::job_card_status)"#,
            )
            .bind(j.id).bind(j.company_id).bind(j.work_order_id).bind(j.operation_id).bind(j.workstation_id)
            .bind(j.total_time_mins).bind(j.hour_rate).bind(j.operating_cost),
        )
        .await?;
        Ok(())
    }

    /// Read a job card joined to its work order — everything `complete_job_card` needs to decide and
    /// to post.
    ///
    /// ID-only: no company argument to scope from up front, so the join rides the REQUEST-dedicated
    /// connection carrying the caller's `app.company_id` — RLS fences it. The caller then binds the
    /// job card's own company onto the completion transaction.
    pub async fn find_completion_source(
        &self,
        pool: &PgPool,
        job_card_id: Uuid,
    ) -> Result<Option<JobCardCompletionRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT j.company_id, j.work_order_id, j.operating_cost, j.status::text AS status,
                          w.wip_account_id, w.conversion_cost_account_id, w.work_order_number, w.status::text AS wo_status
                   FROM manufacturing.job_cards j
                   JOIN manufacturing.work_orders w ON w.id = j.work_order_id
                   WHERE j.id=$1 AND (j.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(job_card_id),
        ).await?;
        Ok(row.map(|r| JobCardCompletionRow {
            company_id: r.get("company_id"),
            work_order_id: r.get("work_order_id"),
            operating_cost: r.get("operating_cost"),
            status: r.get("status"),
            wip_account_id: r.get("wip_account_id"),
            conversion_cost_account_id: r.get("conversion_cost_account_id"),
            work_order_number: r.get("work_order_number"),
            work_order_status: r.get("wo_status"),
        }))
    }

    /// THE COMPLETION GATE: open → completed. Returns rows affected (1 = this caller won; 0 = it was
    /// completed concurrently and the GL post deduped).
    ///
    /// The `status='open'` predicate is the once-only guard on the conversion charge. Takes the
    /// CALLER'S connection so the gate and the work order's cost accumulation commit as ONE unit; the
    /// caller binds the company on it (`bind_company_on`) before calling — don't re-bind.
    pub async fn gate_complete(
        &self,
        conn: &mut sqlx::PgConnection,
        job_card_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.job_cards SET status='completed'::job_card_status
               WHERE id=$1 AND status='open'::job_card_status"#,
        )
        .bind(job_card_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(JobCardRepository, JobCard, soft_delete);
