//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod workstation_repository;
mod operation_repository;
mod bom_repository;
mod bom_item_repository;
mod bom_operation_repository;
mod work_order_repository;
mod work_order_item_repository;
mod job_card_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use workstation_repository::WorkstationRepository;
pub use operation_repository::OperationRepository;
pub use bom_repository::BomRepository;
pub use bom_item_repository::BomItemRepository;
pub use bom_operation_repository::BomOperationRepository;
pub use work_order_repository::WorkOrderRepository;
pub use work_order_item_repository::WorkOrderItemRepository;
pub use job_card_repository::JobCardRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written manufacturing SQL's parameter/projection types. Their repositories are declared
// `user_owned` in metaphor.codegen.yaml; these types mirror COLUMNS, not entities.
pub use bom_repository::NewBomRow;
pub use bom_item_repository::{BomComponentRow, NewBomItemRow};
pub use bom_operation_repository::NewBomOperationRow;
pub use work_order_repository::{NewWorkOrderRow, ReleaseSourceRow, WorkOrderRow};
pub use work_order_item_repository::{NewWorkOrderItemRow, WorkOrderRequirementRow};
pub use job_card_repository::{JobCardCompletionRow, NewJobCardRow};
// END CUSTOM
