//! Repository for Operation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Operation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Operation;

/// Table name for Operation entities
pub const TABLE_NAME: &str = "manufacturing.operations";

/// Repository for Operation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OperationRepository(
    backbone_orm::GenericCrudRepository<Operation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OperationRepository {
    type Target = backbone_orm::GenericCrudRepository<Operation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OperationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OperationRepository, Operation, soft_delete);
