//! Repository for SubcontractMoLink entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SubcontractMoLink, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SubcontractMoLink;

/// Table name for SubcontractMoLink entities
pub const TABLE_NAME: &str = "manufacturing.subcontract_mo_links";

/// Repository for SubcontractMoLink entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubcontractMoLinkRepository(
    backbone_orm::GenericCrudRepository<SubcontractMoLink, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubcontractMoLinkRepository {
    type Target = backbone_orm::GenericCrudRepository<SubcontractMoLink, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubcontractMoLinkRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SubcontractMoLinkRepository, SubcontractMoLink, soft_delete);
