//! Repository for WorkOrder entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written WorkOrder SQL statement — including the three
//! transition gates (release / consume / receive) that are the once-only guards on the WIP posts
//! (4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::WorkOrder;

/// Table name for WorkOrder entities
pub const TABLE_NAME: &str = "manufacturing.work_orders";

/// Repository for WorkOrder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkOrderRepository(
    backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkOrderRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkOrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a work-order insert writes.
///
/// Mirrors the raw column shape rather than the `WorkOrder` entity: `status` is not a parameter —
/// the statement pins `'draft'::work_order_status` so a new work order can only ever start as a
/// draft — and the cost/produced accumulators start at their column defaults, moved only by the
/// gates below.
pub struct NewWorkOrderRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub work_order_number: &'a str,
    pub item_id: Uuid,
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
}

/// The work-order header `release_work_order` reads BEFORE it opens its transaction — the company
/// must be known to bind the scope. `status` is read as `::text` so an unknown state fails the draft
/// check rather than panicking in a decode.
pub struct ReleaseSourceRow {
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub status: String,
}

/// The full work-order projection the execution path reads (`load_wo`).
pub struct WorkOrderRow {
    pub company_id: Uuid,
    pub work_order_number: String,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub produced_qty: Decimal,
    pub status: String,
    pub raw_material_cost: Decimal,
    pub operating_cost: Decimal,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
}

/// Hand-written WorkOrder SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl WorkOrderRepository {
    /// Insert a draft work order.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company
    /// is on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate work-order number into a domain error.
    pub async fn insert_draft(
        &self,
        pool: &PgPool,
        o: &NewWorkOrderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO manufacturing.work_orders
                     (id, company_id, work_order_number, item_id, bom_id, quantity, status,
                      wip_warehouse_id, fg_warehouse_id, wip_account_id, fg_account_id,
                      raw_material_account_id, conversion_cost_account_id)
                   VALUES ($1,$2,$3,$4,$5,$6,'draft'::work_order_status,$7,$8,$9,$10,$11,$12)"#,
            )
            .bind(o.id).bind(o.company_id).bind(o.work_order_number).bind(o.item_id).bind(o.bom_id)
            .bind(o.quantity).bind(o.wip_warehouse_id).bind(o.fg_warehouse_id).bind(o.wip_account_id)
            .bind(o.fg_account_id).bind(o.raw_material_account_id).bind(o.conversion_cost_account_id),
        )
        .await?;
        Ok(())
    }

    /// Read the header `release_work_order` needs before it can open its transaction.
    ///
    /// ID-only: no company argument to scope from up front, so this read rides the REQUEST-dedicated
    /// connection carrying the caller's `app.company_id` — RLS fences it so another company's work
    /// order simply isn't found. This read is deliberately OUTSIDE the release transaction: its
    /// company is what the caller then binds onto that transaction.
    pub async fn find_release_source(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
    ) -> Result<Option<ReleaseSourceRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, item_id, bom_id, quantity, status::text AS status
                   FROM manufacturing.work_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(wo_id),
        ).await?;
        Ok(row.map(|r| ReleaseSourceRow {
            company_id: r.get("company_id"),
            item_id: r.get("item_id"),
            bom_id: r.get("bom_id"),
            quantity: r.get("quantity"),
            status: r.get("status"),
        }))
    }

    /// THE RELEASE GATE: draft → released. Returns rows affected (1 = this caller won).
    ///
    /// This statement — not the header read above — is the once-only guard: the `status='draft'`
    /// predicate is what makes a concurrent/repeat release a no-op, so the BOM explosion is written
    /// exactly once. Takes the CALLER'S connection so the gate and the explosion commit as ONE unit;
    /// the caller binds the company on it (`bind_company_on`) before calling — don't re-bind.
    pub async fn gate_release(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders SET status='released'::work_order_status
               WHERE id=$1 AND status='draft'::work_order_status"#,
        )
        .bind(wo_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// THE CONSUME GATE: released → in_process, accumulating the issued raw-material value. Returns
    /// rows affected (1 = this caller won; 0 = someone else consumed concurrently and the GL post
    /// deduped, so don't double-book state).
    ///
    /// Takes the CALLER'S connection so the gate and the per-line consumption commit as ONE unit; the
    /// caller binds the company on it (`bind_company_on`) before calling — don't re-bind.
    pub async fn gate_consume(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        raw_value: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders
               SET status='in_process'::work_order_status, raw_material_cost = raw_material_cost + $2
               WHERE id=$1 AND status='released'::work_order_status"#,
        )
        .bind(wo_id)
        .bind(raw_value)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// THE RECEIVE GATE: advance produced qty, completing the work order once it reaches the ordered
    /// quantity. Returns rows affected (1 = this caller won; 0 = another receive won the race, and
    /// its side effects deduped ours — not an error).
    ///
    /// The `produced_qty + $2 <= quantity` predicate is the over-produce bound, enforced at the DB
    /// under concurrency rather than only by the service's pre-check. Takes the CALLER'S connection;
    /// the caller binds the company on it (`bind_company_on`) before calling — don't re-bind.
    pub async fn gate_receive(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        produced_qty: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders
               SET produced_qty = produced_qty + $2,
                   status = CASE WHEN produced_qty + $2 >= quantity THEN 'completed'::work_order_status
                                 ELSE status END
               WHERE id=$1 AND status='in_process'::work_order_status AND produced_qty + $2 <= quantity"#,
        )
        .bind(wo_id)
        .bind(produced_qty)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Accumulate a completed job card's conversion cost onto the work order.
    ///
    /// Takes the CALLER'S connection so it lands in the same transaction as the job card's own
    /// completion gate — the charge and the gate must not be split, or a retry could double-charge.
    pub async fn add_operating_cost(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        cost: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE manufacturing.work_orders SET operating_cost = operating_cost + $2 WHERE id=$1"#,
        )
        .bind(wo_id)
        .bind(cost)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a work order's full execution projection.
    ///
    /// ID-only: no company argument — the read rides the request-dedicated connection, so RLS fences
    /// it to the caller's tenant. Callers that are EVENT-driven (not on a request) must wrap the call
    /// in `with_company_scope(Some(event.company_id))` or this read fails closed.
    pub async fn load(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
    ) -> Result<Option<WorkOrderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, work_order_number, item_id, quantity, produced_qty,
                          status::text AS status, raw_material_cost, operating_cost,
                          wip_warehouse_id, fg_warehouse_id, wip_account_id, fg_account_id,
                          raw_material_account_id, conversion_cost_account_id
                   FROM manufacturing.work_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(wo_id),
        ).await?;
        Ok(row.map(|r| WorkOrderRow {
            company_id: r.get("company_id"),
            work_order_number: r.get("work_order_number"),
            item_id: r.get("item_id"),
            quantity: r.get("quantity"),
            produced_qty: r.get("produced_qty"),
            status: r.get("status"),
            raw_material_cost: r.get("raw_material_cost"),
            operating_cost: r.get("operating_cost"),
            wip_warehouse_id: r.get("wip_warehouse_id"),
            fg_warehouse_id: r.get("fg_warehouse_id"),
            wip_account_id: r.get("wip_account_id"),
            fg_account_id: r.get("fg_account_id"),
            raw_material_account_id: r.get("raw_material_account_id"),
            conversion_cost_account_id: r.get("conversion_cost_account_id"),
        }))
    }
}

backbone_core::impl_crud_repository!(WorkOrderRepository, WorkOrder, soft_delete);
