//! Repository for WorkOrder entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written WorkOrder SQL statement — including the four
//! transition gates (confirm / consume / receive / cancel) that are the once-only guards on the
//! WIP posts (4-layer rule: services orchestrate and own the unit of work, repositories hold the
//! SQL).
//!
//! State vocabulary (hybrid 6-state): `confirm` and `cancel` are the hand-gated direct writes;
//! `progress` is derived by the consume gate, `to_close`/`done` by the receive gate's accumulator
//! CASE. Availability lives ONLY in `reservation_state` — a projection column owned by the
//! inventory side, written through `write_reservation_state`.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::{company_scope, org_scope};

use crate::domain::entity::WorkOrder;
use crate::domain::entity::ReservationState;

/// Table name for WorkOrder entities
pub const TABLE_NAME: &str = "manufacturing.work_orders";

/// Repository for WorkOrder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkOrderRepository(
    backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkOrderRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkOrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a work-order insert writes.
///
/// Mirrors the raw column shape rather than the `WorkOrder` entity: `status` is not a parameter —
/// the statement pins `'draft'::work_order_state` so a new work order can only ever start as a
/// draft — and the cost/produced accumulators start at their column defaults, moved only by the
/// gates below. `product_category_id` snapshots the item's category at creation: it selects the
/// costing defaults that fill any unset account override.
pub struct NewWorkOrderRow<'a> {
    pub id: Uuid,
    pub work_order_number: &'a str,
    pub item_id: Uuid,
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub product_category_id: Option<Uuid>,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
}

/// The work-order header `confirm_work_order` reads BEFORE it opens its transaction. `status` is
/// read as `::text` so an unknown state fails the draft check rather than panicking in a decode.
pub struct ConfirmSourceRow {
    pub item_id: Uuid,
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub status: String,
}

/// The full work-order projection the execution path reads (`load_wo`).
pub struct WorkOrderRow {
    pub work_order_number: String,
    pub item_id: Uuid,
    pub bom_id: Uuid,
    pub quantity: Decimal,
    pub produced_qty: Decimal,
    pub status: String,
    pub reservation_state: Option<String>,
    pub product_category_id: Option<Uuid>,
    pub raw_material_cost: Decimal,
    pub operating_cost: Decimal,
    pub wip_warehouse_id: Option<Uuid>,
    pub fg_warehouse_id: Option<Uuid>,
    pub wip_account_id: Option<Uuid>,
    pub fg_account_id: Option<Uuid>,
    pub raw_material_account_id: Option<Uuid>,
    pub conversion_cost_account_id: Option<Uuid>,
}

/// Hand-written WorkOrder SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl WorkOrderRepository {
    /// Insert a draft work order.
    ///
    /// A write outside any transaction: takes the pool and runs `org_scope::execute_scoped`, which
    /// binds the ambient org scope (the composing service sets it per request) so the decorator's
    /// org-unit fill and fence see the INSERT. Undecorated (module tests) the insert runs plain
    /// (ADR-0029).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate work-order number into a domain error.
    pub async fn insert_draft(
        &self,
        pool: &PgPool,
        o: &NewWorkOrderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO manufacturing.work_orders
                     (id, work_order_number, item_id, bom_id, quantity, status,
                      product_category_id,
                      wip_warehouse_id, fg_warehouse_id, wip_account_id, fg_account_id,
                      raw_material_account_id, conversion_cost_account_id)
                   VALUES ($1,$2,$3,$4,$5,'draft'::work_order_state,$6,$7,$8,$9,$10,$11,$12)"#,
            )
            .bind(o.id).bind(o.work_order_number).bind(o.item_id).bind(o.bom_id)
            .bind(o.quantity).bind(o.product_category_id)
            .bind(o.wip_warehouse_id).bind(o.fg_warehouse_id).bind(o.wip_account_id)
            .bind(o.fg_account_id).bind(o.raw_material_account_id).bind(o.conversion_cost_account_id),
        )
        .await?;
        Ok(())
    }

    /// Insert a work order DIRECTLY in `confirmed` — the hidden subcontract MO mint.
    ///
    /// Takes the CALLER'S connection so the mint, its exploded component requirements and the
    /// subcontract link row commit as ONE unit (a minted order without its link would break the
    /// replay backstop). The caller relays the ambient org scope onto that connection
    /// (`relay_ambient_scope`) before calling — don't re-bind (ADR-0029). `status` is pinned by the
    /// statement: only the subcontract receipt path may create an order that skips draft.
    pub async fn insert_confirmed(
        &self,
        conn: &mut sqlx::PgConnection,
        o: &NewWorkOrderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO manufacturing.work_orders
                 (id, work_order_number, item_id, bom_id, quantity, status,
                  product_category_id,
                  wip_warehouse_id, fg_warehouse_id, wip_account_id, fg_account_id,
                  raw_material_account_id, conversion_cost_account_id)
               VALUES ($1,$2,$3,$4,$5,'confirmed'::work_order_state,$6,$7,$8,$9,$10,$11,$12)"#,
        )
        .bind(o.id).bind(o.work_order_number).bind(o.item_id).bind(o.bom_id)
        .bind(o.quantity).bind(o.product_category_id)
        .bind(o.wip_warehouse_id).bind(o.fg_warehouse_id).bind(o.wip_account_id)
        .bind(o.fg_account_id).bind(o.raw_material_account_id).bind(o.conversion_cost_account_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the header `confirm_work_order` needs before it can open its transaction.
    ///
    /// ID-only (ADR-0029): the read rides the request-dedicated connection — under the composed
    /// decorator the org fence scopes it to the caller's unit; undecorated (module tests) the read
    /// runs plain. This read is deliberately OUTSIDE the confirm transaction: it decides whether
    /// the confirm may proceed at all before any state is claimed.
    pub async fn find_confirm_source(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
    ) -> Result<Option<ConfirmSourceRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT item_id, bom_id, quantity, status::text AS status
                   FROM manufacturing.work_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(wo_id),
        ).await?;
        Ok(row.map(|r| ConfirmSourceRow {
            item_id: r.get("item_id"),
            bom_id: r.get("bom_id"),
            quantity: r.get("quantity"),
            status: r.get("status"),
        }))
    }

    /// THE CONFIRM GATE: draft → confirmed. Returns rows affected (1 = this caller won).
    ///
    /// This statement — not the header read above — is the once-only guard: the `status='draft'`
    /// predicate is what makes a concurrent/repeat confirm a no-op, so the BOM explosion is written
    /// exactly once. Takes the CALLER'S connection so the gate and the explosion commit as ONE unit;
    /// the caller relays the ambient org scope on it (`relay_ambient_scope`) before calling — don't
    /// re-bind (ADR-0029).
    pub async fn gate_confirm(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders SET status='confirmed'::work_order_state
               WHERE id=$1 AND status='draft'::work_order_state"#,
        )
        .bind(wo_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// THE CONSUME GATE: confirmed → progress, accumulating the issued raw-material value. Returns
    /// rows affected (1 = this caller won; 0 = someone else consumed concurrently and the GL post
    /// deduped, so don't double-book state).
    ///
    /// `progress` is DERIVED: the first issue of materials to WIP is what puts the order in
    /// progress — there is no hand-written "start" verb. Takes the CALLER'S connection so the gate
    /// and the per-line consumption commit as ONE unit; the caller relays the ambient org scope on
    /// it (`relay_ambient_scope`) before calling — don't re-bind (ADR-0029).
    pub async fn gate_consume(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        raw_value: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders
               SET status='progress'::work_order_state, raw_material_cost = raw_material_cost + $2
               WHERE id=$1 AND status='confirmed'::work_order_state"#,
        )
        .bind(wo_id)
        .bind(raw_value)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// THE RECEIVE GATE: advance produced qty, deriving to_close/done from the accumulator.
    /// Returns rows affected (1 = this caller won; 0 = another receive won the race, and its side
    /// effects deduped ours — not an error).
    ///
    /// The derived states are computed by the CASE, never passed in: a partial receipt leaves the
    /// order `to_close` (0 < produced < ordered), a full one completes it to `done`. The
    /// `produced_qty + $2 <= quantity` predicate is the over-produce bound, enforced at the DB
    /// under concurrency rather than only by the service's pre-check. The WHERE predicate admits
    /// `progress` AND `to_close` — receipts only count against an order that has consumed
    /// materials, and a partially-received order stays receivable until it is done.
    /// Takes the CALLER'S connection; the caller relays the ambient org scope on it
    /// (`relay_ambient_scope`) before calling — don't re-bind (ADR-0029).
    pub async fn gate_receive(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        produced_qty: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders
               SET produced_qty = produced_qty + $2,
                   status = CASE WHEN produced_qty + $2 >= quantity THEN 'done'::work_order_state
                                 ELSE 'to_close'::work_order_state END
               WHERE id=$1 AND status IN ('progress'::work_order_state, 'to_close'::work_order_state)
                 AND produced_qty + $2 <= quantity"#,
        )
        .bind(wo_id)
        .bind(produced_qty)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// THE CANCEL GATE: draft|confirmed → cancel. Returns rows affected (1 = this caller won;
    /// 0 = the order had already left the cancellable pair).
    ///
    /// Cancel is direct-write and terminal (sticky). Orders that have consumed materials
    /// (progress) or received goods (to_close/done) carry WIP and stock that a state flip cannot
    /// unwind — the predicate refuses them and the service turns the 0 into a LOUD InvalidState.
    /// Takes the CALLER'S connection so cancel lands atomically with its event publish.
    pub async fn gate_cancel(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders SET status='cancel'::work_order_state
               WHERE id=$1 AND status IN ('draft'::work_order_state, 'confirmed'::work_order_state)"#,
        )
        .bind(wo_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Write the reservation_state projection (waiting | confirmed | assigned).
    ///
    /// Availability is expressed ONLY here — no field named `availability` exists anywhere in the
    /// module. The value is inventory-owned: the reservation endpoint (and only it) writes this
    /// column; work-order verbs never read it into a decision. Idempotent by value: rewriting the
    /// same state is a no-op.
    pub async fn write_reservation_state(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
        state: ReservationState,
    ) -> Result<u64, sqlx::Error> {
        // The availability projection AND its derived job-card flip land as ONE unit: the work
        // order's reservation_state is written, and every not-yet-started job card of the order
        // flips ready<->blocked from it (assigned -> ready; waiting|confirmed -> blocked).
        // Cards in progress/done/cancel are never touched — the flip only applies to queued work.
        let flip_to = if state == ReservationState::Assigned { "ready" } else { "blocked" };
        let mut tx = pool.begin().await?;
        // Tenancy posture (ADR-0029): the module owns no scoping column — the composing service's
        // tenancy decorator does. Relay the AMBIENT request scope onto this transaction when the
        // caller bound one, so the decorator's org-unit fill and its row-level fence see this
        // transaction's statements. An undecorated deployment has no ambient scope and skips this.
        if let Some(scope) = org_scope::current_org_scope() {
            org_scope::bind_org_scope_on(&mut tx, &scope).await?;
        }
        let done = sqlx::query(
            r#"UPDATE manufacturing.work_orders SET reservation_state=$2
               WHERE id=$1"#,
        )
        .bind(wo_id)
        .bind(state)
        .execute(&mut *tx)
        .await?;
        sqlx::query(
            r#"UPDATE manufacturing.job_cards
                  SET status = $2::job_card_state
                WHERE work_order_id=$1
                  AND status IN ('ready'::job_card_state, 'blocked'::job_card_state)"#,
        )
        .bind(wo_id)
        .bind(flip_to)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(done.rows_affected())
    }

    /// Accumulate a completed job card's conversion cost onto the work order.
    ///
    /// Takes the CALLER'S connection so it lands in the same transaction as the job card's own
    /// completion gate — the charge and the gate must not be split, or a retry could double-charge.
    pub async fn add_operating_cost(
        &self,
        conn: &mut sqlx::PgConnection,
        wo_id: Uuid,
        cost: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE manufacturing.work_orders SET operating_cost = operating_cost + $2 WHERE id=$1"#,
        )
        .bind(wo_id)
        .bind(cost)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a work order's full execution projection.
    ///
    /// ID-only (ADR-0029): the read rides the request-dedicated connection — under the composed
    /// decorator the org fence scopes it to the caller's unit; undecorated (module tests) the read
    /// runs plain.
    pub async fn load(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
    ) -> Result<Option<WorkOrderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT work_order_number, item_id, bom_id, quantity, produced_qty,
                          status::text AS status, reservation_state::text AS reservation_state,
                          product_category_id, raw_material_cost, operating_cost,
                          wip_warehouse_id, fg_warehouse_id, wip_account_id, fg_account_id,
                          raw_material_account_id, conversion_cost_account_id
                   FROM manufacturing.work_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(wo_id),
        ).await?;
        Ok(row.map(|r| WorkOrderRow {
            work_order_number: r.get("work_order_number"),
            item_id: r.get("item_id"),
            bom_id: r.get("bom_id"),
            quantity: r.get("quantity"),
            produced_qty: r.get("produced_qty"),
            status: r.get("status"),
            reservation_state: r.get("reservation_state"),
            product_category_id: r.get("product_category_id"),
            raw_material_cost: r.get("raw_material_cost"),
            operating_cost: r.get("operating_cost"),
            wip_warehouse_id: r.get("wip_warehouse_id"),
            fg_warehouse_id: r.get("fg_warehouse_id"),
            wip_account_id: r.get("wip_account_id"),
            fg_account_id: r.get("fg_account_id"),
            raw_material_account_id: r.get("raw_material_account_id"),
            conversion_cost_account_id: r.get("conversion_cost_account_id"),
        }))
    }
}

backbone_core::impl_crud_repository!(WorkOrderRepository, WorkOrder, soft_delete);
