//! Repository for WorkOrder entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WorkOrder;

/// Table name for WorkOrder entities
pub const TABLE_NAME: &str = "manufacturing.work_orders";

/// Repository for WorkOrder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkOrderRepository(
    backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkOrderRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkOrder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkOrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WorkOrderRepository, WorkOrder, soft_delete);
