//! Repository for WorkOrderItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written WorkOrderItem SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkOrderItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::WorkOrderItem;

/// Table name for WorkOrderItem entities
pub const TABLE_NAME: &str = "manufacturing.work_order_items";

/// Repository for WorkOrderItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkOrderItemRepository(
    backbone_orm::GenericCrudRepository<WorkOrderItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkOrderItemRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkOrderItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkOrderItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a material-requirement insert writes. `consumed_qty` is not a parameter — the
/// statement pins it to 0; only [`WorkOrderItemRepository::add_consumed_qty`] ever moves it.
pub struct NewWorkOrderItemRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub work_order_id: Uuid,
    pub item_id: Uuid,
    pub required_qty: Decimal,
    pub rate: Decimal,
}

/// One material requirement and how much of it has been issued so far.
pub struct WorkOrderRequirementRow {
    pub id: Uuid,
    pub item_id: Uuid,
    pub required_qty: Decimal,
    pub consumed_qty: Decimal,
}

/// Hand-written WorkOrderItem SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl WorkOrderItemRepository {
    /// Insert one exploded material requirement.
    ///
    /// Takes the CALLER'S connection so the requirement commits in the SAME transaction as the
    /// release gate — that gate is what makes this write once-only. The caller binds the company on
    /// that connection (`bind_company_on`) before calling — don't re-bind. The explicit `company_id`
    /// bind (denormalized from the parent work order) stays as defense-in-depth behind the RLS fence
    /// (ADR-0010 Decision A).
    pub async fn insert_requirement(
        &self,
        conn: &mut sqlx::PgConnection,
        r: &NewWorkOrderItemRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO manufacturing.work_order_items
                 (id, company_id, work_order_id, item_id, required_qty, consumed_qty, rate)
               VALUES ($1,$2,$3,$4,$5,0,$6)"#,
        )
        .bind(r.id).bind(r.company_id).bind(r.work_order_id).bind(r.item_id).bind(r.required_qty).bind(r.rate)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a work order's material requirements.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_all_rows_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the
    /// work order was already read, so its company is known.
    pub async fn list_requirements(
        &self,
        pool: &PgPool,
        wo_id: Uuid,
    ) -> Result<Vec<WorkOrderRequirementRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, item_id, required_qty, consumed_qty FROM manufacturing.work_order_items
                   WHERE work_order_id=$1"#,
            )
            .bind(wo_id),
        ).await?;
        Ok(rows.iter().map(|r| WorkOrderRequirementRow {
            id: r.get("id"),
            item_id: r.get("item_id"),
            required_qty: r.get("required_qty"),
            consumed_qty: r.get("consumed_qty"),
        }).collect())
    }

    /// Record that a requirement was issued to WIP.
    ///
    /// Takes the CALLER'S connection so it lands in the same transaction as the consume gate — the
    /// gate is what makes these writes once-only; splitting them would let a retry double-consume.
    pub async fn add_consumed_qty(
        &self,
        conn: &mut sqlx::PgConnection,
        line_id: Uuid,
        qty: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE manufacturing.work_order_items SET consumed_qty = consumed_qty + $2 WHERE id=$1"#,
        )
        .bind(line_id)
        .bind(qty)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(WorkOrderItemRepository, WorkOrderItem, soft_delete);
