//! Validator for BomSubcontractor entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BomSubcontractor>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::BomSubcontractor;

/// Validator type alias for BomSubcontractor entities.
pub type BomSubcontractorValidator = EntityValidator<BomSubcontractor>;

/// Build a validator for BomSubcontractor with all schema-defined field rules.
pub fn bom_subcontractor_validator() -> BomSubcontractorValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
