//! Validator for CategoryCostingDefaults entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CategoryCostingDefaults>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CategoryCostingDefaults;

/// Validator type alias for CategoryCostingDefaults entities.
pub type CategoryCostingDefaultsValidator = EntityValidator<CategoryCostingDefaults>;

/// Build a validator for CategoryCostingDefaults with all schema-defined field rules.
pub fn category_costing_defaults_validator() -> CategoryCostingDefaultsValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
