//! Validator for Operation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Operation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Operation;

/// Validator type alias for Operation entities.
pub type OperationValidator = EntityValidator<Operation>;

/// Build a validator for Operation with all schema-defined field rules.
pub fn operation_validator() -> OperationValidator {
    EntityValidator::new()
        .rule(RequiredString::new("operation_name", |e: &Operation| &e.operation_name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
