//! Validator for WorkstationProductivity entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WorkstationProductivity>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::WorkstationProductivity;

/// Validator type alias for WorkstationProductivity entities.
pub type WorkstationProductivityValidator = EntityValidator<WorkstationProductivity>;

/// Build a validator for WorkstationProductivity with all schema-defined field rules.
pub fn workstation_productivity_validator() -> WorkstationProductivityValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("description", |e: &WorkstationProductivity| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
