//! Validator for WorkstationLoss entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WorkstationLoss>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::WorkstationLoss;

/// Validator type alias for WorkstationLoss entities.
pub type WorkstationLossValidator = EntityValidator<WorkstationLoss>;

/// Build a validator for WorkstationLoss with all schema-defined field rules.
pub fn workstation_loss_validator() -> WorkstationLossValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &WorkstationLoss| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
