//! Validator for WorkOrderItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WorkOrderItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::WorkOrderItem;

/// Validator type alias for WorkOrderItem entities.
pub type WorkOrderItemValidator = EntityValidator<WorkOrderItem>;

/// Build a validator for WorkOrderItem with all schema-defined field rules.
pub fn work_order_item_validator() -> WorkOrderItemValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
