//! Auth configuration for Bom handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Bom>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BomService;
use crate::domain::entity::Bom;

/// Permission string constants for Bom operations.
pub mod permissions {
    pub const LIST:        &str = "bom:list";
    pub const READ:        &str = "bom:read";
    pub const CREATE:      &str = "bom:create";
    pub const UPDATE:      &str = "bom:update";
    pub const DELETE:      &str = "bom:delete";
    pub const RESTORE:     &str = "bom:restore";
    pub const TRASH:       &str = "bom:trash";
    pub const EMPTY_TRASH: &str = "bom:empty_trash";
    pub const BULK_CREATE: &str = "bom:bulk_create";
    pub const UPSERT:      &str = "bom:upsert";
}

/// Resource policy for Bom — maps CRUD actions to permission strings.
pub struct BomPolicy;

#[async_trait]
impl ResourcePolicy<Bom> for BomPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Bom,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Bom handlers.
///
/// Wraps `BomService` and checks `BomPolicy` before delegating.
pub type BomGuard = PermissionGuard<Bom>;

/// Service-integrated permission guard for Bom (for use in generated handlers).
pub type BomServiceGuard = ServicePermissionGuard<Bom, BomService, BomPolicy>;

// <<< CUSTOM
// END CUSTOM
