//! Auth configuration for BomOperation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BomOperation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BomOperationService;
use crate::domain::entity::BomOperation;

/// Permission string constants for BomOperation operations.
pub mod permissions {
    pub const LIST:        &str = "bom_operation:list";
    pub const READ:        &str = "bom_operation:read";
    pub const CREATE:      &str = "bom_operation:create";
    pub const UPDATE:      &str = "bom_operation:update";
    pub const DELETE:      &str = "bom_operation:delete";
    pub const RESTORE:     &str = "bom_operation:restore";
    pub const TRASH:       &str = "bom_operation:trash";
    pub const EMPTY_TRASH: &str = "bom_operation:empty_trash";
    pub const BULK_CREATE: &str = "bom_operation:bulk_create";
    pub const UPSERT:      &str = "bom_operation:upsert";
}

/// Resource policy for BomOperation — maps CRUD actions to permission strings.
pub struct BomOperationPolicy;

#[async_trait]
impl ResourcePolicy<BomOperation> for BomOperationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BomOperation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BomOperation handlers.
///
/// Wraps `BomOperationService` and checks `BomOperationPolicy` before delegating.
pub type BomOperationGuard = PermissionGuard<BomOperation>;

/// Service-integrated permission guard for BomOperation (for use in generated handlers).
pub type BomOperationServiceGuard = ServicePermissionGuard<BomOperation, BomOperationService, BomOperationPolicy>;

// <<< CUSTOM
// END CUSTOM
