//! Auth configuration for JobCard handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<JobCard>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::JobCardService;
use crate::domain::entity::JobCard;

/// Permission string constants for JobCard operations.
pub mod permissions {
    pub const LIST:        &str = "job_card:list";
    pub const READ:        &str = "job_card:read";
    pub const CREATE:      &str = "job_card:create";
    pub const UPDATE:      &str = "job_card:update";
    pub const DELETE:      &str = "job_card:delete";
    pub const RESTORE:     &str = "job_card:restore";
    pub const TRASH:       &str = "job_card:trash";
    pub const EMPTY_TRASH: &str = "job_card:empty_trash";
    pub const BULK_CREATE: &str = "job_card:bulk_create";
    pub const UPSERT:      &str = "job_card:upsert";
}

/// Resource policy for JobCard — maps CRUD actions to permission strings.
pub struct JobCardPolicy;

#[async_trait]
impl ResourcePolicy<JobCard> for JobCardPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &JobCard,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for JobCard handlers.
///
/// Wraps `JobCardService` and checks `JobCardPolicy` before delegating.
pub type JobCardGuard = PermissionGuard<JobCard>;

/// Service-integrated permission guard for JobCard (for use in generated handlers).
pub type JobCardServiceGuard = ServicePermissionGuard<JobCard, JobCardService, JobCardPolicy>;

// <<< CUSTOM
// END CUSTOM
