//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod workstation_auth;
pub mod operation_auth;
pub mod bom_auth;
pub mod bom_item_auth;
pub mod bom_operation_auth;
pub mod work_order_auth;
pub mod work_order_item_auth;
pub mod job_card_auth;

pub use workstation_auth::{WorkstationPolicy, WorkstationGuard, WorkstationServiceGuard};
pub use operation_auth::{OperationPolicy, OperationGuard, OperationServiceGuard};
pub use bom_auth::{BomPolicy, BomGuard, BomServiceGuard};
pub use bom_item_auth::{BomItemPolicy, BomItemGuard, BomItemServiceGuard};
pub use bom_operation_auth::{BomOperationPolicy, BomOperationGuard, BomOperationServiceGuard};
pub use work_order_auth::{WorkOrderPolicy, WorkOrderGuard, WorkOrderServiceGuard};
pub use work_order_item_auth::{WorkOrderItemPolicy, WorkOrderItemGuard, WorkOrderItemServiceGuard};
pub use job_card_auth::{JobCardPolicy, JobCardGuard, JobCardServiceGuard};

// <<< CUSTOM
// END CUSTOM
