//! Auth configuration for Operation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Operation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OperationService;
use crate::domain::entity::Operation;

/// Permission string constants for Operation operations.
pub mod permissions {
    pub const LIST:        &str = "operation:list";
    pub const READ:        &str = "operation:read";
    pub const CREATE:      &str = "operation:create";
    pub const UPDATE:      &str = "operation:update";
    pub const DELETE:      &str = "operation:delete";
    pub const RESTORE:     &str = "operation:restore";
    pub const TRASH:       &str = "operation:trash";
    pub const EMPTY_TRASH: &str = "operation:empty_trash";
    pub const BULK_CREATE: &str = "operation:bulk_create";
    pub const UPSERT:      &str = "operation:upsert";
}

/// Resource policy for Operation — maps CRUD actions to permission strings.
pub struct OperationPolicy;

#[async_trait]
impl ResourcePolicy<Operation> for OperationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Operation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Operation handlers.
///
/// Wraps `OperationService` and checks `OperationPolicy` before delegating.
pub type OperationGuard = PermissionGuard<Operation>;

/// Service-integrated permission guard for Operation (for use in generated handlers).
pub type OperationServiceGuard = ServicePermissionGuard<Operation, OperationService, OperationPolicy>;

// <<< CUSTOM
// END CUSTOM
