//! Auth configuration for WorkOrder handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<WorkOrder>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::WorkOrderService;
use crate::domain::entity::WorkOrder;

/// Permission string constants for WorkOrder operations.
pub mod permissions {
    pub const LIST:        &str = "work_order:list";
    pub const READ:        &str = "work_order:read";
    pub const CREATE:      &str = "work_order:create";
    pub const UPDATE:      &str = "work_order:update";
    pub const DELETE:      &str = "work_order:delete";
    pub const RESTORE:     &str = "work_order:restore";
    pub const TRASH:       &str = "work_order:trash";
    pub const EMPTY_TRASH: &str = "work_order:empty_trash";
    pub const BULK_CREATE: &str = "work_order:bulk_create";
    pub const UPSERT:      &str = "work_order:upsert";
}

/// Resource policy for WorkOrder — maps CRUD actions to permission strings.
pub struct WorkOrderPolicy;

#[async_trait]
impl ResourcePolicy<WorkOrder> for WorkOrderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &WorkOrder,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for WorkOrder handlers.
///
/// Wraps `WorkOrderService` and checks `WorkOrderPolicy` before delegating.
pub type WorkOrderGuard = PermissionGuard<WorkOrder>;

/// Service-integrated permission guard for WorkOrder (for use in generated handlers).
pub type WorkOrderServiceGuard = ServicePermissionGuard<WorkOrder, WorkOrderService, WorkOrderPolicy>;

// <<< CUSTOM
// END CUSTOM
