//! BomOperation API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the BomOperation CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BOMOPERATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for BomOperation
pub struct BomOperationTestData;

impl TestDataGenerator for BomOperationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "bom_id": Uuid::new_v4().to_string(),
            "operation_id": Uuid::new_v4().to_string(),
            "workstation_id": Uuid::new_v4().to_string(),
            "time_in_mins": 0,
            "hour_rate": 0,
            "operating_cost": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "bom_id": Uuid::new_v4().to_string(),
            "operation_id": Uuid::new_v4().to_string(),
            "workstation_id": Uuid::new_v4().to_string(),
            "time_in_mins": 0,
            "hour_rate": 0,
            "operating_cost": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/boms", &super::bom_api_test::BomTestData).await {
            deps.push(("bom_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/operations", &super::operation_api_test::OperationTestData).await {
            deps.push(("operation_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/workstations", &super::workstation_api_test::WorkstationTestData).await {
            deps.push(("workstation_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BOMOPERATION API TEST
// ============================================================================

/// BomOperation API test suite
pub struct BomOperationApiTest {
    inner: GenericCrudTest<BomOperationTestData>,
}

impl BomOperationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/bom_operations", "BomOperation");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BomOperationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BomOperationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bom_operation_crud() {
        let mut test = BomOperationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add BomOperation specific tests here
// <<< CUSTOM TESTS END >>>
