//! Bom API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Bom CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BOM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Bom
pub struct BomTestData;

impl TestDataGenerator for BomTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "bom_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "quantity": 0,
            "uom": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "raw_material_cost": 0,
            "operating_cost": 0,
            "total_cost": 0,
            "is_active": false,
            "is_default": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "bom_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "quantity": 0,
            "uom": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "raw_material_cost": 0,
            "operating_cost": 0,
            "total_cost": 0,
            "is_active": false,
            "is_default": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// BOM API TEST
// ============================================================================

/// Bom API test suite
pub struct BomApiTest {
    inner: GenericCrudTest<BomTestData>,
}

impl BomApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/boms", "Bom");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BomTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BomApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bom_crud() {
        let mut test = BomApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Bom specific tests here
// <<< CUSTOM TESTS END >>>
