//! CategoryCostingDefaults API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CategoryCostingDefaults CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CATEGORYCOSTINGDEFAULTS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CategoryCostingDefaults
pub struct CategoryCostingDefaultsTestData;

impl TestDataGenerator for CategoryCostingDefaultsTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "product_category_id": Uuid::new_v4().to_string(),
            "wip_account_id": null,
            "fg_account_id": null,
            "raw_material_account_id": null,
            "conversion_cost_account_id": null,
            "subcontract_interim_account_id": null,
            "cost_variance_account_id": null,
            "inventory_loss_account_id": null,
            "repair_expense_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "product_category_id": Uuid::new_v4().to_string(),
            "wip_account_id": null,
            "fg_account_id": null,
            "raw_material_account_id": null,
            "conversion_cost_account_id": null,
            "subcontract_interim_account_id": null,
            "cost_variance_account_id": null,
            "inventory_loss_account_id": null,
            "repair_expense_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CATEGORYCOSTINGDEFAULTS API TEST
// ============================================================================

/// CategoryCostingDefaults API test suite
pub struct CategoryCostingDefaultsApiTest {
    inner: GenericCrudTest<CategoryCostingDefaultsTestData>,
}

impl CategoryCostingDefaultsApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/category_costing_defaults", "CategoryCostingDefaults");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CategoryCostingDefaultsTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CategoryCostingDefaultsApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_category_costing_defaults_crud() {
        let mut test = CategoryCostingDefaultsApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CategoryCostingDefaults specific tests here
// <<< CUSTOM TESTS END >>>
