//! SubcontractMoLink API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SubcontractMoLink CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SUBCONTRACTMOLINK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SubcontractMoLink
pub struct SubcontractMoLinkTestData;

impl TestDataGenerator for SubcontractMoLinkTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "purchase_order_id": Uuid::new_v4().to_string(),
            "work_order_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "purchase_order_id": Uuid::new_v4().to_string(),
            "work_order_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/work_orders", &super::work_order_api_test::WorkOrderTestData).await {
            deps.push(("work_order_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SUBCONTRACTMOLINK API TEST
// ============================================================================

/// SubcontractMoLink API test suite
pub struct SubcontractMoLinkApiTest {
    inner: GenericCrudTest<SubcontractMoLinkTestData>,
}

impl SubcontractMoLinkApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/subcontract_mo_links", "SubcontractMoLink");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SubcontractMoLinkTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SubcontractMoLinkApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_subcontract_mo_link_crud() {
        let mut test = SubcontractMoLinkApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SubcontractMoLink specific tests here
// <<< CUSTOM TESTS END >>>
