//! WorkstationProductivity API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the WorkstationProductivity CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// WORKSTATIONPRODUCTIVITY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for WorkstationProductivity
pub struct WorkstationProductivityTestData;

impl TestDataGenerator for WorkstationProductivityTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "workstation_id": Uuid::new_v4().to_string(),
            "job_card_id": null,
            "loss_id": Uuid::new_v4().to_string(),
            "date_start": now,
            "date_end": null,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "workstation_id": Uuid::new_v4().to_string(),
            "job_card_id": null,
            "loss_id": Uuid::new_v4().to_string(),
            "date_start": now,
            "date_end": null,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/workstations", &super::workstation_api_test::WorkstationTestData).await {
            deps.push(("workstation_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/workstation_losses", &super::workstation_loss_api_test::WorkstationLossTestData).await {
            deps.push(("loss_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// WORKSTATIONPRODUCTIVITY API TEST
// ============================================================================

/// WorkstationProductivity API test suite
pub struct WorkstationProductivityApiTest {
    inner: GenericCrudTest<WorkstationProductivityTestData>,
}

impl WorkstationProductivityApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/workstation_productivity", "WorkstationProductivity");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, WorkstationProductivityTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for WorkstationProductivityApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_workstation_productivity_crud() {
        let mut test = WorkstationProductivityApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add WorkstationProductivity specific tests here
// <<< CUSTOM TESTS END >>>
