//! WorkOrder API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the WorkOrder CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// WORKORDER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for WorkOrder
pub struct WorkOrderTestData;

impl TestDataGenerator for WorkOrderTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "work_order_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "item_id": Uuid::new_v4().to_string(),
            "bom_id": Uuid::new_v4().to_string(),
            "quantity": 0,
            "produced_qty": 0,
            "status": "draft",
            "raw_material_cost": 0,
            "operating_cost": 0,
            "wip_warehouse_id": null,
            "fg_warehouse_id": null,
            "wip_account_id": null,
            "fg_account_id": null,
            "raw_material_account_id": null,
            "conversion_cost_account_id": null,
            "planned_start_date": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "work_order_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "item_id": Uuid::new_v4().to_string(),
            "bom_id": Uuid::new_v4().to_string(),
            "quantity": 0,
            "produced_qty": 0,
            "status": "draft",
            "raw_material_cost": 0,
            "operating_cost": 0,
            "wip_warehouse_id": null,
            "fg_warehouse_id": null,
            "wip_account_id": null,
            "fg_account_id": null,
            "raw_material_account_id": null,
            "conversion_cost_account_id": null,
            "planned_start_date": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/boms", &super::bom_api_test::BomTestData).await {
            deps.push(("bom_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// WORKORDER API TEST
// ============================================================================

/// WorkOrder API test suite
pub struct WorkOrderApiTest {
    inner: GenericCrudTest<WorkOrderTestData>,
}

impl WorkOrderApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/work_orders", "WorkOrder");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, WorkOrderTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for WorkOrderApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_work_order_crud() {
        let mut test = WorkOrderApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add WorkOrder specific tests here
// <<< CUSTOM TESTS END >>>
