//! Manufacturing Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::WorkstationService;
use crate::application::service::OperationService;
use crate::application::service::BomService;
use crate::application::service::BomItemService;
use crate::application::service::BomOperationService;
use crate::application::service::WorkOrderService;
use crate::application::service::WorkOrderItemService;
use crate::application::service::JobCardService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Workstation service
    pub workstation_service: Arc<WorkstationService>,
    /// Operation service
    pub operation_service: Arc<OperationService>,
    /// Bom service
    pub bom_service: Arc<BomService>,
    /// BomItem service
    pub bom_item_service: Arc<BomItemService>,
    /// BomOperation service
    pub bom_operation_service: Arc<BomOperationService>,
    /// WorkOrder service
    pub work_order_service: Arc<WorkOrderService>,
    /// WorkOrderItem service
    pub work_order_item_service: Arc<WorkOrderItemService>,
    /// JobCard service
    pub job_card_service: Arc<JobCardService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        workstation_service: Arc<WorkstationService>,
        operation_service: Arc<OperationService>,
        bom_service: Arc<BomService>,
        bom_item_service: Arc<BomItemService>,
        bom_operation_service: Arc<BomOperationService>,
        work_order_service: Arc<WorkOrderService>,
        work_order_item_service: Arc<WorkOrderItemService>,
        job_card_service: Arc<JobCardService>
    ) -> Self {
        Self {
            workstation_service,
            operation_service,
            bom_service,
            bom_item_service,
            bom_operation_service,
            work_order_service,
            work_order_item_service,
            job_card_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::ManufacturingModule) -> Self {
        Self {
            workstation_service: module.workstation_service.clone(),
            operation_service: module.operation_service.clone(),
            bom_service: module.bom_service.clone(),
            bom_item_service: module.bom_item_service.clone(),
            bom_operation_service: module.bom_operation_service.clone(),
            work_order_service: module.work_order_service.clone(),
            work_order_item_service: module.work_order_item_service.clone(),
            job_card_service: module.job_card_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    workstation_service: Option<Arc<WorkstationService>>,
    operation_service: Option<Arc<OperationService>>,
    bom_service: Option<Arc<BomService>>,
    bom_item_service: Option<Arc<BomItemService>>,
    bom_operation_service: Option<Arc<BomOperationService>>,
    work_order_service: Option<Arc<WorkOrderService>>,
    work_order_item_service: Option<Arc<WorkOrderItemService>>,
    job_card_service: Option<Arc<JobCardService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Workstation service.
    pub fn with_workstation_service(mut self, service: Arc<WorkstationService>) -> Self {
        self.workstation_service = Some(service);
        self
    }

    /// Set the Operation service.
    pub fn with_operation_service(mut self, service: Arc<OperationService>) -> Self {
        self.operation_service = Some(service);
        self
    }

    /// Set the Bom service.
    pub fn with_bom_service(mut self, service: Arc<BomService>) -> Self {
        self.bom_service = Some(service);
        self
    }

    /// Set the BomItem service.
    pub fn with_bom_item_service(mut self, service: Arc<BomItemService>) -> Self {
        self.bom_item_service = Some(service);
        self
    }

    /// Set the BomOperation service.
    pub fn with_bom_operation_service(mut self, service: Arc<BomOperationService>) -> Self {
        self.bom_operation_service = Some(service);
        self
    }

    /// Set the WorkOrder service.
    pub fn with_work_order_service(mut self, service: Arc<WorkOrderService>) -> Self {
        self.work_order_service = Some(service);
        self
    }

    /// Set the WorkOrderItem service.
    pub fn with_work_order_item_service(mut self, service: Arc<WorkOrderItemService>) -> Self {
        self.work_order_item_service = Some(service);
        self
    }

    /// Set the JobCard service.
    pub fn with_job_card_service(mut self, service: Arc<JobCardService>) -> Self {
        self.job_card_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            workstation_service: self.workstation_service.expect("workstation_service is required"),
            operation_service: self.operation_service.expect("operation_service is required"),
            bom_service: self.bom_service.expect("bom_service is required"),
            bom_item_service: self.bom_item_service.expect("bom_item_service is required"),
            bom_operation_service: self.bom_operation_service.expect("bom_operation_service is required"),
            work_order_service: self.work_order_service.expect("work_order_service is required"),
            work_order_item_service: self.work_order_item_service.expect("work_order_item_service is required"),
            job_card_service: self.job_card_service.expect("job_card_service is required"),
        }
    }
}
