//! Manufacturing Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Manufacturing exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use manufacturing::exports::{WorkstationDto, ManufacturingQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `WorkstationDto` - Data transfer object for Workstation
/// - `WorkstationSummary` - Summary view of Workstation
/// - `WorkstationId` - Type-safe ID wrapper
/// - `OperationDto` - Data transfer object for Operation
/// - `OperationSummary` - Summary view of Operation
/// - `OperationId` - Type-safe ID wrapper
/// - `BomDto` - Data transfer object for Bom
/// - `BomSummary` - Summary view of Bom
/// - `BomId` - Type-safe ID wrapper
/// - `BomItemDto` - Data transfer object for BomItem
/// - `BomItemSummary` - Summary view of BomItem
/// - `BomItemId` - Type-safe ID wrapper
/// - `BomOperationDto` - Data transfer object for BomOperation
/// - `BomOperationSummary` - Summary view of BomOperation
/// - `BomOperationId` - Type-safe ID wrapper
/// - `WorkOrderDto` - Data transfer object for WorkOrder
/// - `WorkOrderSummary` - Summary view of WorkOrder
/// - `WorkOrderId` - Type-safe ID wrapper
/// - `WorkOrderItemDto` - Data transfer object for WorkOrderItem
/// - `WorkOrderItemSummary` - Summary view of WorkOrderItem
/// - `WorkOrderItemId` - Type-safe ID wrapper
/// - `JobCardDto` - Data transfer object for JobCard
/// - `JobCardSummary` - Summary view of JobCard
/// - `JobCardId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `ManufacturingQueryService` - Read-only queries
///
/// ## Public Events
/// - `WorkstationCreatedEvent` - Published when Workstation is created
/// - `WorkstationUpdatedEvent` - Published when Workstation is updated
/// - `WorkstationDeletedEvent` - Published when Workstation is deleted
/// - `OperationCreatedEvent` - Published when Operation is created
/// - `OperationUpdatedEvent` - Published when Operation is updated
/// - `OperationDeletedEvent` - Published when Operation is deleted
/// - `BomCreatedEvent` - Published when Bom is created
/// - `BomUpdatedEvent` - Published when Bom is updated
/// - `BomDeletedEvent` - Published when Bom is deleted
/// - `BomItemCreatedEvent` - Published when BomItem is created
/// - `BomItemUpdatedEvent` - Published when BomItem is updated
/// - `BomItemDeletedEvent` - Published when BomItem is deleted
/// - `BomOperationCreatedEvent` - Published when BomOperation is created
/// - `BomOperationUpdatedEvent` - Published when BomOperation is updated
/// - `BomOperationDeletedEvent` - Published when BomOperation is deleted
/// - `WorkOrderCreatedEvent` - Published when WorkOrder is created
/// - `WorkOrderUpdatedEvent` - Published when WorkOrder is updated
/// - `WorkOrderDeletedEvent` - Published when WorkOrder is deleted
/// - `WorkOrderItemCreatedEvent` - Published when WorkOrderItem is created
/// - `WorkOrderItemUpdatedEvent` - Published when WorkOrderItem is updated
/// - `WorkOrderItemDeletedEvent` - Published when WorkOrderItem is deleted
/// - `JobCardCreatedEvent` - Published when JobCard is created
/// - `JobCardUpdatedEvent` - Published when JobCard is updated
/// - `JobCardDeletedEvent` - Published when JobCard is deleted
pub struct ExportSummary;
