//! Manufacturing Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// <<< CUSTOM
// Hand-written validated command surface (`src/write_api.rs` is declared under
// `user_owned` in metaphor.codegen.yaml). Declared inside this marker so schema
// regeneration preserves the declaration alongside the generated module list.
pub mod write_api;
// END CUSTOM
// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::WorkstationService;
pub use application::service::WorkstationLossService;
pub use application::service::WorkstationProductivityService;
pub use application::service::OperationService;
pub use application::service::BomService;
pub use application::service::BomItemService;
pub use application::service::BomOperationService;
pub use application::service::BomByproductService;
pub use application::service::BomSubcontractorService;
pub use application::service::CategoryCostingDefaultsService;
pub use application::service::RepairOrderService;
pub use application::service::RepairPartService;
pub use application::service::RepairTagService;
pub use application::service::UnbuildOrderService;
pub use application::service::WorkOrderService;
pub use application::service::WorkOrderItemService;
pub use application::service::JobCardService;
pub use application::service::SubcontractMoLinkService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Manufacturing module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let manufacturing = ManufacturingModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = manufacturing.all_crud_routes();
/// ```
pub struct ManufacturingModule {
    pub(crate) workstation_service: Arc<WorkstationService>,
    pub(crate) workstation_loss_service: Arc<WorkstationLossService>,
    pub(crate) workstation_productivity_service: Arc<WorkstationProductivityService>,
    pub(crate) operation_service: Arc<OperationService>,
    pub(crate) bom_service: Arc<BomService>,
    pub(crate) bom_item_service: Arc<BomItemService>,
    pub(crate) bom_operation_service: Arc<BomOperationService>,
    pub(crate) bom_byproduct_service: Arc<BomByproductService>,
    pub(crate) bom_subcontractor_service: Arc<BomSubcontractorService>,
    pub(crate) category_costing_defaults_service: Arc<CategoryCostingDefaultsService>,
    pub(crate) repair_order_service: Arc<RepairOrderService>,
    pub(crate) repair_part_service: Arc<RepairPartService>,
    pub(crate) repair_tag_service: Arc<RepairTagService>,
    pub(crate) unbuild_order_service: Arc<UnbuildOrderService>,
    pub(crate) work_order_service: Arc<WorkOrderService>,
    pub(crate) work_order_item_service: Arc<WorkOrderItemService>,
    pub(crate) job_card_service: Arc<JobCardService>,
    pub(crate) subcontract_mo_link_service: Arc<SubcontractMoLinkService>,
    // <<< CUSTOM FIELDS
    pub(crate) manufacturing_write_service:
        Arc<crate::application::service::ManufacturingWriteService>,
    // END CUSTOM
}

impl ManufacturingModule {
    /// Create a new module builder
    pub fn builder() -> ManufacturingModuleBuilder {
        ManufacturingModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_workstation_routes,
            create_workstation_loss_routes,
            create_workstation_productivity_routes,
            create_operation_routes,
            create_bom_routes,
            create_bom_item_routes,
            create_bom_operation_routes,
            create_bom_byproduct_routes,
            create_bom_subcontractor_routes,
            create_category_costing_defaults_routes,
            create_repair_order_routes,
            create_repair_part_routes,
            create_repair_tag_routes,
            create_unbuild_order_routes,
            create_work_order_routes,
            create_work_order_item_routes,
            create_job_card_routes,
            create_subcontract_mo_link_routes,
        };

        Router::new()
            .merge(create_workstation_routes(self.workstation_service.clone()))
            .merge(create_workstation_loss_routes(self.workstation_loss_service.clone()))
            .merge(create_workstation_productivity_routes(self.workstation_productivity_service.clone()))
            .merge(create_operation_routes(self.operation_service.clone()))
            .merge(create_bom_routes(self.bom_service.clone()))
            .merge(create_bom_item_routes(self.bom_item_service.clone()))
            .merge(create_bom_operation_routes(self.bom_operation_service.clone()))
            .merge(create_bom_byproduct_routes(self.bom_byproduct_service.clone()))
            .merge(create_bom_subcontractor_routes(self.bom_subcontractor_service.clone()))
            .merge(create_category_costing_defaults_routes(self.category_costing_defaults_service.clone()))
            .merge(create_repair_order_routes(self.repair_order_service.clone()))
            .merge(create_repair_part_routes(self.repair_part_service.clone()))
            .merge(create_repair_tag_routes(self.repair_tag_service.clone()))
            .merge(create_unbuild_order_routes(self.unbuild_order_service.clone()))
            .merge(create_work_order_routes(self.work_order_service.clone()))
            .merge(create_work_order_item_routes(self.work_order_item_service.clone()))
            .merge(create_job_card_routes(self.job_card_service.clone()))
            .merge(create_subcontract_mo_link_routes(self.subcontract_mo_link_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_workstation_read_routes,
            create_workstation_loss_read_routes,
            create_workstation_productivity_read_routes,
            create_operation_read_routes,
            create_bom_read_routes,
            create_bom_item_read_routes,
            create_bom_operation_read_routes,
            create_bom_byproduct_read_routes,
            create_bom_subcontractor_read_routes,
            create_category_costing_defaults_read_routes,
            create_repair_order_read_routes,
            create_repair_part_read_routes,
            create_repair_tag_read_routes,
            create_unbuild_order_read_routes,
            create_work_order_read_routes,
            create_work_order_item_read_routes,
            create_job_card_read_routes,
            create_subcontract_mo_link_read_routes,
        };

        Router::new()
            .merge(create_workstation_read_routes(self.workstation_service.clone()))
            .merge(create_workstation_loss_read_routes(self.workstation_loss_service.clone()))
            .merge(create_workstation_productivity_read_routes(self.workstation_productivity_service.clone()))
            .merge(create_operation_read_routes(self.operation_service.clone()))
            .merge(create_bom_read_routes(self.bom_service.clone()))
            .merge(create_bom_item_read_routes(self.bom_item_service.clone()))
            .merge(create_bom_operation_read_routes(self.bom_operation_service.clone()))
            .merge(create_bom_byproduct_read_routes(self.bom_byproduct_service.clone()))
            .merge(create_bom_subcontractor_read_routes(self.bom_subcontractor_service.clone()))
            .merge(create_category_costing_defaults_read_routes(self.category_costing_defaults_service.clone()))
            .merge(create_repair_order_read_routes(self.repair_order_service.clone()))
            .merge(create_repair_part_read_routes(self.repair_part_service.clone()))
            .merge(create_repair_tag_read_routes(self.repair_tag_service.clone()))
            .merge(create_unbuild_order_read_routes(self.unbuild_order_service.clone()))
            .merge(create_work_order_read_routes(self.work_order_service.clone()))
            .merge(create_work_order_item_read_routes(self.work_order_item_service.clone()))
            .merge(create_job_card_read_routes(self.job_card_service.clone()))
            .merge(create_subcontract_mo_link_read_routes(self.subcontract_mo_link_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated manufacturing execution engine (release → consume → operate → receive),
    /// which rolls up BOM cost and emits the three WIP/FG GL posts so a Work Order's WIP nets to
    /// zero on completion.
    ///
    /// This is **not** mounted by [`Self::all_crud_routes`] — that exposes *unguarded* generic CRUD
    /// that bypasses every manufacturing invariant (a `PATCH status→completed` there posts no GL).
    /// To serve validated writes over HTTP, compose the command router from [`write_api`]:
    ///
    /// ```ignore
    /// let m = ManufacturingModule::builder().with_database(pool).build()?;
    /// let deps = write_api::ManufacturingWriteDeps {
    ///     write_service: m.write_service(),
    ///     inventory: Arc::new(my_inventory_adapter),   // you own stock — supply a real InventoryPort
    ///     gl:        Arc::new(my_gl_adapter),          // you own the ledger — supply a real GlPostSink
    ///     events:    Arc::new(LoggingSink),            // or your bus sink
    /// };
    /// let app = Router::new()
    ///     .merge(/* your read routes */)
    ///     .merge(write_api::create_manufacturing_write_routes().with_state(deps));
    /// ```
    ///
    /// The ports are caller-supplied per call: a no-op `GlPostSink` silently drops the WIP postings
    /// (it compiles, it looks done, WIP leaks) — supply real adapters from the composing service.
    pub fn write_service(
        &self,
    ) -> Arc<crate::application::service::ManufacturingWriteService> {
        self.manufacturing_write_service.clone()
    }
    // END CUSTOM
}

/// Builder for ManufacturingModule
pub struct ManufacturingModuleBuilder {
    db_pool: Option<PgPool>,
}

impl ManufacturingModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<ManufacturingModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Workstation service
        let workstation_repository = Arc::new(WorkstationRepository::new(db_pool.clone()));
        let workstation_service = Arc::new(WorkstationService::with_repository(workstation_repository.clone()));

        // WorkstationLoss service
        let workstation_loss_repository = Arc::new(WorkstationLossRepository::new(db_pool.clone()));
        let workstation_loss_service = Arc::new(WorkstationLossService::with_repository(workstation_loss_repository.clone()));

        // WorkstationProductivity service
        let workstation_productivity_repository = Arc::new(WorkstationProductivityRepository::new(db_pool.clone()));
        let workstation_productivity_service = Arc::new(WorkstationProductivityService::with_repository(workstation_productivity_repository.clone()));

        // Operation service
        let operation_repository = Arc::new(OperationRepository::new(db_pool.clone()));
        let operation_service = Arc::new(OperationService::with_repository(operation_repository.clone()));

        // Bom service
        let bom_repository = Arc::new(BomRepository::new(db_pool.clone()));
        let bom_service = Arc::new(BomService::with_repository(bom_repository.clone()));

        // BomItem service
        let bom_item_repository = Arc::new(BomItemRepository::new(db_pool.clone()));
        let bom_item_service = Arc::new(BomItemService::with_repository(bom_item_repository.clone()));

        // BomOperation service
        let bom_operation_repository = Arc::new(BomOperationRepository::new(db_pool.clone()));
        let bom_operation_service = Arc::new(BomOperationService::with_repository(bom_operation_repository.clone()));

        // BomByproduct service
        let bom_byproduct_repository = Arc::new(BomByproductRepository::new(db_pool.clone()));
        let bom_byproduct_service = Arc::new(BomByproductService::with_repository(bom_byproduct_repository.clone()));

        // BomSubcontractor service
        let bom_subcontractor_repository = Arc::new(BomSubcontractorRepository::new(db_pool.clone()));
        let bom_subcontractor_service = Arc::new(BomSubcontractorService::with_repository(bom_subcontractor_repository.clone()));

        // CategoryCostingDefaults service
        let category_costing_defaults_repository = Arc::new(CategoryCostingDefaultsRepository::new(db_pool.clone()));
        let category_costing_defaults_service = Arc::new(CategoryCostingDefaultsService::with_repository(category_costing_defaults_repository.clone()));

        // RepairOrder service
        let repair_order_repository = Arc::new(RepairOrderRepository::new(db_pool.clone()));
        let repair_order_service = Arc::new(RepairOrderService::with_repository(repair_order_repository.clone()));

        // RepairPart service
        let repair_part_repository = Arc::new(RepairPartRepository::new(db_pool.clone()));
        let repair_part_service = Arc::new(RepairPartService::with_repository(repair_part_repository.clone()));

        // RepairTag service
        let repair_tag_repository = Arc::new(RepairTagRepository::new(db_pool.clone()));
        let repair_tag_service = Arc::new(RepairTagService::with_repository(repair_tag_repository.clone()));

        // UnbuildOrder service
        let unbuild_order_repository = Arc::new(UnbuildOrderRepository::new(db_pool.clone()));
        let unbuild_order_service = Arc::new(UnbuildOrderService::with_repository(unbuild_order_repository.clone()));

        // WorkOrder service
        let work_order_repository = Arc::new(WorkOrderRepository::new(db_pool.clone()));
        let work_order_service = Arc::new(WorkOrderService::with_repository(work_order_repository.clone()));

        // WorkOrderItem service
        let work_order_item_repository = Arc::new(WorkOrderItemRepository::new(db_pool.clone()));
        let work_order_item_service = Arc::new(WorkOrderItemService::with_repository(work_order_item_repository.clone()));

        // JobCard service
        let job_card_repository = Arc::new(JobCardRepository::new(db_pool.clone()));
        let job_card_service = Arc::new(JobCardService::with_repository(job_card_repository.clone()));

        // SubcontractMoLink service
        let subcontract_mo_link_repository = Arc::new(SubcontractMoLinkRepository::new(db_pool.clone()));
        let subcontract_mo_link_service = Arc::new(SubcontractMoLinkService::with_repository(subcontract_mo_link_repository.clone()));

        // <<< CUSTOM
        // The validated execution engine. It shares this module's pool (same RLS connection
        // story as the generic services); the GL/inventory ports are supplied per call by the
        // composing service via `write_api::ManufacturingWriteDeps`.
        let manufacturing_write_service = Arc::new(
            crate::application::service::ManufacturingWriteService::new(db_pool.clone()),
        );
        // END CUSTOM

        Ok(ManufacturingModule {
            workstation_service,
            workstation_loss_service,
            workstation_productivity_service,
            operation_service,
            bom_service,
            bom_item_service,
            bom_operation_service,
            bom_byproduct_service,
            bom_subcontractor_service,
            category_costing_defaults_service,
            repair_order_service,
            repair_part_service,
            repair_tag_service,
            unbuild_order_service,
            work_order_service,
            work_order_item_service,
            job_card_service,
            subcontract_mo_link_service,
            // <<< CUSTOM
            manufacturing_write_service,
            // END CUSTOM
        })
    }
}

impl Default for ManufacturingModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
