//! Use case type aliases for BomOperation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBomOperationDto, UpdateBomOperationDto};
use crate::application::service::BomOperationService;
use crate::domain::entity::BomOperation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBomOperationUseCase = CreateUseCase<BomOperation, CreateBomOperationDto, BomOperationService>;
pub type UpdateBomOperationUseCase = UpdateUseCase<BomOperation, UpdateBomOperationDto, BomOperationService>;
pub type GetBomOperationUseCase    = GetUseCase<BomOperation, BomOperationService>;
pub type DeleteBomOperationUseCase = DeleteUseCase<BomOperation, BomOperationService>;
pub type ListBomOperationUseCase   = ListUseCase<BomOperation, BomOperationService>;

// <<< CUSTOM
// END CUSTOM
