//! Use case type aliases for BomItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBomItemDto, UpdateBomItemDto};
use crate::application::service::BomItemService;
use crate::domain::entity::BomItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBomItemUseCase = CreateUseCase<BomItem, CreateBomItemDto, BomItemService>;
pub type UpdateBomItemUseCase = UpdateUseCase<BomItem, UpdateBomItemDto, BomItemService>;
pub type GetBomItemUseCase    = GetUseCase<BomItem, BomItemService>;
pub type DeleteBomItemUseCase = DeleteUseCase<BomItem, BomItemService>;
pub type ListBomItemUseCase   = ListUseCase<BomItem, BomItemService>;

// <<< CUSTOM
// END CUSTOM
