//! Use case type aliases for Operation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOperationDto, UpdateOperationDto};
use crate::application::service::OperationService;
use crate::domain::entity::Operation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOperationUseCase = CreateUseCase<Operation, CreateOperationDto, OperationService>;
pub type UpdateOperationUseCase = UpdateUseCase<Operation, UpdateOperationDto, OperationService>;
pub type GetOperationUseCase    = GetUseCase<Operation, OperationService>;
pub type DeleteOperationUseCase = DeleteUseCase<Operation, OperationService>;
pub type ListOperationUseCase   = ListUseCase<Operation, OperationService>;

// <<< CUSTOM
// END CUSTOM
