//! Use case type aliases for Workstation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateWorkstationDto, UpdateWorkstationDto};
use crate::application::service::WorkstationService;
use crate::domain::entity::Workstation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateWorkstationUseCase = CreateUseCase<Workstation, CreateWorkstationDto, WorkstationService>;
pub type UpdateWorkstationUseCase = UpdateUseCase<Workstation, UpdateWorkstationDto, WorkstationService>;
pub type GetWorkstationUseCase    = GetUseCase<Workstation, WorkstationService>;
pub type DeleteWorkstationUseCase = DeleteUseCase<Workstation, WorkstationService>;
pub type ListWorkstationUseCase   = ListUseCase<Workstation, WorkstationService>;

// <<< CUSTOM
// END CUSTOM
