//! Use case type aliases for WorkOrderItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateWorkOrderItemDto, UpdateWorkOrderItemDto};
use crate::application::service::WorkOrderItemService;
use crate::domain::entity::WorkOrderItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateWorkOrderItemUseCase = CreateUseCase<WorkOrderItem, CreateWorkOrderItemDto, WorkOrderItemService>;
pub type UpdateWorkOrderItemUseCase = UpdateUseCase<WorkOrderItem, UpdateWorkOrderItemDto, WorkOrderItemService>;
pub type GetWorkOrderItemUseCase    = GetUseCase<WorkOrderItem, WorkOrderItemService>;
pub type DeleteWorkOrderItemUseCase = DeleteUseCase<WorkOrderItem, WorkOrderItemService>;
pub type ListWorkOrderItemUseCase   = ListUseCase<WorkOrderItem, WorkOrderItemService>;

// <<< CUSTOM
// END CUSTOM
