//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod workstation_handler;
pub mod operation_handler;
pub mod bom_handler;
pub mod bom_item_handler;
pub mod bom_operation_handler;
pub mod work_order_handler;
pub mod work_order_item_handler;
pub mod job_card_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use workstation_handler::{create_workstation_routes, create_workstation_read_routes, create_workstation_write_routes};
pub use operation_handler::{create_operation_routes, create_operation_read_routes, create_operation_write_routes};
pub use bom_handler::{create_bom_routes, create_bom_read_routes, create_bom_write_routes};
pub use bom_item_handler::{create_bom_item_routes, create_bom_item_read_routes, create_bom_item_write_routes};
pub use bom_operation_handler::{create_bom_operation_routes, create_bom_operation_read_routes, create_bom_operation_write_routes};
pub use work_order_handler::{create_work_order_routes, create_work_order_read_routes, create_work_order_write_routes};
pub use work_order_item_handler::{create_work_order_item_routes, create_work_order_item_read_routes, create_work_order_item_write_routes};
pub use job_card_handler::{create_job_card_routes, create_job_card_read_routes, create_job_card_write_routes};
// <<< CUSTOM
// END CUSTOM
